// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core 7ec04293c426).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

namespace Oblodai.Contract;

/// <summary>Which snapshot of the gateway contract this build was generated from.</summary>
public static class ContractVersion
{
    /// <summary>Gateway commit that exported the snapshot.</summary>
    public const string CoreCommit = "7ec04293c4264faa121409b1715c2e8fcd349f32";

    /// <summary>When the snapshot was exported.</summary>
    public const string ExportedAt = "2026-08-26T10:50:02Z";

    /// <summary>SHA-256 of <c>contract/contract.json</c>.</summary>
    public const string Hash = "c2d8d4b733eaa4a876a1f8d0525cb838df380ee37fc0d03a711dab77e80b2829";
}
