// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core 7b8eb828b9ec).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

namespace Oblodai.Contract;

/// <summary>Which snapshot of the gateway contract this build was generated from.</summary>
public static class ContractVersion
{
    /// <summary>Gateway commit that exported the snapshot.</summary>
    public const string CoreCommit = "7b8eb828b9ec3bbaff44755ad784881e533ec4fb";

    /// <summary>When the snapshot was exported.</summary>
    public const string ExportedAt = "2026-08-25T22:08:54Z";

    /// <summary>SHA-256 of <c>contract/contract.json</c>.</summary>
    public const string Hash = "e09b495accaeacda1aa889a8c56b0e9ee18b5236dc3c2c29222e7ee849e7c5ee";
}
