// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core bfca971cce71).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

namespace Oblodai.Contract;

/// <summary>Which snapshot of the gateway contract this build was generated from.</summary>
public static class ContractVersion
{
    /// <summary>Gateway commit that exported the snapshot.</summary>
    public const string CoreCommit = "bfca971cce71d090ba9f7083616b4568d5568868";

    /// <summary>When the snapshot was exported.</summary>
    public const string ExportedAt = "2026-08-26T00:50:13Z";

    /// <summary>SHA-256 of <c>contract/contract.json</c>.</summary>
    public const string Hash = "e0271464937d8171858e13af226c4e35914752f98e84ccba344cd31b79f07dd9";
}
