// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core 7ec04293c426).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

using System.Text.Json.Serialization;

namespace Oblodai.Contract;

/// <summary>Invoice lifecycle: <c>select → created → confirm_check → paid | paid_over | wrong_amount | expired | cancelled</c>.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<PaymentStatus>))]
public readonly record struct PaymentStatus(string Value) : IStringValue<PaymentStatus>
{
    /// <summary><c>select</c></summary>
    public static readonly PaymentStatus Select = new("select");

    /// <summary><c>created</c></summary>
    public static readonly PaymentStatus Created = new("created");

    /// <summary><c>confirm_check</c></summary>
    public static readonly PaymentStatus ConfirmCheck = new("confirm_check");

    /// <summary><c>paid</c></summary>
    public static readonly PaymentStatus Paid = new("paid");

    /// <summary><c>paid_over</c></summary>
    public static readonly PaymentStatus PaidOver = new("paid_over");

    /// <summary><c>wrong_amount</c></summary>
    public static readonly PaymentStatus WrongAmount = new("wrong_amount");

    /// <summary><c>expired</c></summary>
    public static readonly PaymentStatus Expired = new("expired");

    /// <summary><c>cancelled</c></summary>
    public static readonly PaymentStatus Cancelled = new("cancelled");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<PaymentStatus> Known =
    [
        Select, Created, ConfirmCheck, Paid, PaidOver, WrongAmount,
        Expired, Cancelled,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static PaymentStatus FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(PaymentStatus value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a PaymentStatus and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator PaymentStatus(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Payout lifecycle: <c>pending → approved → awaiting_cosign → broadcasting → sent → confirmed | failed | cancelled</c>.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<PayoutStatus>))]
public readonly record struct PayoutStatus(string Value) : IStringValue<PayoutStatus>
{
    /// <summary><c>pending</c></summary>
    public static readonly PayoutStatus Pending = new("pending");

    /// <summary><c>approved</c></summary>
    public static readonly PayoutStatus Approved = new("approved");

    /// <summary><c>awaiting_cosign</c></summary>
    public static readonly PayoutStatus AwaitingCosign = new("awaiting_cosign");

    /// <summary><c>broadcasting</c></summary>
    public static readonly PayoutStatus Broadcasting = new("broadcasting");

    /// <summary><c>sent</c></summary>
    public static readonly PayoutStatus Sent = new("sent");

    /// <summary><c>confirmed</c></summary>
    public static readonly PayoutStatus Confirmed = new("confirmed");

    /// <summary><c>failed</c></summary>
    public static readonly PayoutStatus Failed = new("failed");

    /// <summary><c>cancelled</c></summary>
    public static readonly PayoutStatus Cancelled = new("cancelled");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<PayoutStatus> Known =
    [
        Pending, Approved, AwaitingCosign, Broadcasting, Sent, Confirmed,
        Failed, Cancelled,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static PayoutStatus FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(PayoutStatus value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a PayoutStatus and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator PayoutStatus(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Payout-link (cheque) lifecycle.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<PayoutLinkStatus>))]
public readonly record struct PayoutLinkStatus(string Value) : IStringValue<PayoutLinkStatus>
{
    /// <summary><c>funded</c></summary>
    public static readonly PayoutLinkStatus Funded = new("funded");

    /// <summary><c>claiming</c></summary>
    public static readonly PayoutLinkStatus Claiming = new("claiming");

    /// <summary><c>claimed</c></summary>
    public static readonly PayoutLinkStatus Claimed = new("claimed");

    /// <summary><c>expired</c></summary>
    public static readonly PayoutLinkStatus Expired = new("expired");

    /// <summary><c>cancelled</c></summary>
    public static readonly PayoutLinkStatus Cancelled = new("cancelled");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<PayoutLinkStatus> Known =
    [
        Funded, Claiming, Claimed, Expired, Cancelled,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static PayoutLinkStatus FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(PayoutLinkStatus value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a PayoutLinkStatus and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator PayoutLinkStatus(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Webhook delivery outcome.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<DeliveryStatus>))]
public readonly record struct DeliveryStatus(string Value) : IStringValue<DeliveryStatus>
{
    /// <summary><c>pending</c></summary>
    public static readonly DeliveryStatus Pending = new("pending");

    /// <summary><c>delivered</c></summary>
    public static readonly DeliveryStatus Delivered = new("delivered");

    /// <summary><c>dead</c></summary>
    public static readonly DeliveryStatus Dead = new("dead");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<DeliveryStatus> Known =
    [
        Pending, Delivered, Dead,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static DeliveryStatus FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(DeliveryStatus value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a DeliveryStatus and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator DeliveryStatus(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Settlement networks the gateway supports.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<Network>))]
public readonly record struct Network(string Value) : IStringValue<Network>
{
    /// <summary><c>ethereum</c></summary>
    public static readonly Network Ethereum = new("ethereum");

    /// <summary><c>bsc</c></summary>
    public static readonly Network Bsc = new("bsc");

    /// <summary><c>polygon</c></summary>
    public static readonly Network Polygon = new("polygon");

    /// <summary><c>avalanche</c></summary>
    public static readonly Network Avalanche = new("avalanche");

    /// <summary><c>base</c></summary>
    public static readonly Network Base = new("base");

    /// <summary><c>arbitrum</c></summary>
    public static readonly Network Arbitrum = new("arbitrum");

    /// <summary><c>tron</c></summary>
    public static readonly Network Tron = new("tron");

    /// <summary><c>solana</c></summary>
    public static readonly Network Solana = new("solana");

    /// <summary><c>ton</c></summary>
    public static readonly Network Ton = new("ton");

    /// <summary><c>bitcoin</c></summary>
    public static readonly Network Bitcoin = new("bitcoin");

    /// <summary><c>litecoin</c></summary>
    public static readonly Network Litecoin = new("litecoin");

    /// <summary><c>dogecoin</c></summary>
    public static readonly Network Dogecoin = new("dogecoin");

    /// <summary><c>bitcoincash</c></summary>
    public static readonly Network Bitcoincash = new("bitcoincash");

    /// <summary><c>dash</c></summary>
    public static readonly Network Dash = new("dash");

    /// <summary><c>xrp</c></summary>
    public static readonly Network Xrp = new("xrp");

    /// <summary><c>stellar</c></summary>
    public static readonly Network Stellar = new("stellar");

    /// <summary><c>monero</c></summary>
    public static readonly Network Monero = new("monero");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<Network> Known =
    [
        Ethereum, Bsc, Polygon, Avalanche, Base, Arbitrum,
        Tron, Solana, Ton, Bitcoin, Litecoin, Dogecoin,
        Bitcoincash, Dash, Xrp, Stellar, Monero,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static Network FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(Network value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a Network and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator Network(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Who is asked to bear the network fee on a request.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<FeeBearer>))]
public readonly record struct FeeBearer(string Value) : IStringValue<FeeBearer>
{
    /// <summary><c>recipient</c></summary>
    public static readonly FeeBearer Recipient = new("recipient");

    /// <summary><c>merchant</c></summary>
    public static readonly FeeBearer Merchant = new("merchant");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<FeeBearer> Known =
    [
        Recipient, Merchant,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static FeeBearer FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(FeeBearer value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a FeeBearer and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator FeeBearer(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Who actually bore the fee on a priced result.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<FeeBearerResult>))]
public readonly record struct FeeBearerResult(string Value) : IStringValue<FeeBearerResult>
{
    /// <summary><c>recipient</c></summary>
    public static readonly FeeBearerResult Recipient = new("recipient");

    /// <summary><c>merchant</c></summary>
    public static readonly FeeBearerResult Merchant = new("merchant");

    /// <summary><c>gateway</c></summary>
    public static readonly FeeBearerResult Gateway = new("gateway");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<FeeBearerResult> Known =
    [
        Recipient, Merchant, Gateway,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static FeeBearerResult FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(FeeBearerResult value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a FeeBearerResult and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator FeeBearerResult(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>What an asynchronous batch does when an item fails.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<BatchOnError>))]
public readonly record struct BatchOnError(string Value) : IStringValue<BatchOnError>
{
    /// <summary><c>continue</c></summary>
    public static readonly BatchOnError Continue = new("continue");

    /// <summary><c>stop</c></summary>
    public static readonly BatchOnError Stop = new("stop");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<BatchOnError> Known =
    [
        Continue, Stop,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static BatchOnError FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(BatchOnError value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a BatchOnError and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator BatchOnError(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Kinds of test webhook the gateway can deliver.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<WebhookKind>))]
public readonly record struct WebhookKind(string Value) : IStringValue<WebhookKind>
{
    /// <summary><c>payment</c></summary>
    public static readonly WebhookKind Payment = new("payment");

    /// <summary><c>payout</c></summary>
    public static readonly WebhookKind Payout = new("payout");

    /// <summary><c>wallet</c></summary>
    public static readonly WebhookKind Wallet = new("wallet");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<WebhookKind> Known =
    [
        Payment, Payout, Wallet,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static WebhookKind FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(WebhookKind value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a WebhookKind and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator WebhookKind(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Error families the gateway maps onto HTTP statuses.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<ErrorKind>))]
public readonly record struct ErrorKind(string Value) : IStringValue<ErrorKind>
{
    /// <summary><c>invalid</c></summary>
    public static readonly ErrorKind Invalid = new("invalid");

    /// <summary><c>unauthorized</c></summary>
    public static readonly ErrorKind Unauthorized = new("unauthorized");

    /// <summary><c>forbidden</c></summary>
    public static readonly ErrorKind Forbidden = new("forbidden");

    /// <summary><c>not_found</c></summary>
    public static readonly ErrorKind NotFound = new("not_found");

    /// <summary><c>conflict</c></summary>
    public static readonly ErrorKind Conflict = new("conflict");

    /// <summary><c>rate_limited</c></summary>
    public static readonly ErrorKind RateLimited = new("rate_limited");

    /// <summary><c>unavailable</c></summary>
    public static readonly ErrorKind Unavailable = new("unavailable");

    /// <summary><c>internal</c></summary>
    public static readonly ErrorKind Internal = new("internal");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<ErrorKind> Known =
    [
        Invalid, Unauthorized, Forbidden, NotFound, Conflict, RateLimited,
        Unavailable, Internal,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static ErrorKind FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(ErrorKind value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a ErrorKind and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator ErrorKind(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>How a payment link prices its invoices.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<AmountMode>))]
public readonly record struct AmountMode(string Value) : IStringValue<AmountMode>
{
    /// <summary><c>fixed</c></summary>
    public static readonly AmountMode Fixed = new("fixed");

    /// <summary><c>open</c></summary>
    public static readonly AmountMode Open = new("open");

    /// <summary><c>range</c></summary>
    public static readonly AmountMode Range = new("range");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<AmountMode> Known =
    [
        Fixed, Open, Range,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static AmountMode FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(AmountMode value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a AmountMode and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator AmountMode(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

/// <summary>Webhook event types: <c>invoice.&lt;status&gt;</c>, <c>payout.&lt;status&gt;</c>, <c>wallet.paid</c>.</summary>
/// <param name="Value">The wire value; unknown values are carried through unchanged.</param>
[JsonConverter(typeof(StringValueJsonConverter<EventType>))]
public readonly record struct EventType(string Value) : IStringValue<EventType>
{
    /// <summary><c>invoice.select</c></summary>
    public static readonly EventType InvoiceSelect = new("invoice.select");

    /// <summary><c>invoice.created</c></summary>
    public static readonly EventType InvoiceCreated = new("invoice.created");

    /// <summary><c>invoice.confirm_check</c></summary>
    public static readonly EventType InvoiceConfirmCheck = new("invoice.confirm_check");

    /// <summary><c>invoice.paid</c></summary>
    public static readonly EventType InvoicePaid = new("invoice.paid");

    /// <summary><c>invoice.paid_over</c></summary>
    public static readonly EventType InvoicePaidOver = new("invoice.paid_over");

    /// <summary><c>invoice.wrong_amount</c></summary>
    public static readonly EventType InvoiceWrongAmount = new("invoice.wrong_amount");

    /// <summary><c>invoice.expired</c></summary>
    public static readonly EventType InvoiceExpired = new("invoice.expired");

    /// <summary><c>invoice.cancelled</c></summary>
    public static readonly EventType InvoiceCancelled = new("invoice.cancelled");

    /// <summary><c>payout.pending</c></summary>
    public static readonly EventType PayoutPending = new("payout.pending");

    /// <summary><c>payout.approved</c></summary>
    public static readonly EventType PayoutApproved = new("payout.approved");

    /// <summary><c>payout.awaiting_cosign</c></summary>
    public static readonly EventType PayoutAwaitingCosign = new("payout.awaiting_cosign");

    /// <summary><c>payout.broadcasting</c></summary>
    public static readonly EventType PayoutBroadcasting = new("payout.broadcasting");

    /// <summary><c>payout.sent</c></summary>
    public static readonly EventType PayoutSent = new("payout.sent");

    /// <summary><c>payout.confirmed</c></summary>
    public static readonly EventType PayoutConfirmed = new("payout.confirmed");

    /// <summary><c>payout.failed</c></summary>
    public static readonly EventType PayoutFailed = new("payout.failed");

    /// <summary><c>payout.cancelled</c></summary>
    public static readonly EventType PayoutCancelled = new("payout.cancelled");

    /// <summary><c>wallet.paid</c></summary>
    public static readonly EventType WalletPaid = new("wallet.paid");

    /// <summary>Every value this snapshot knows.</summary>
    public static readonly IReadOnlyList<EventType> Known =
    [
        InvoiceSelect, InvoiceCreated, InvoiceConfirmCheck, InvoicePaid, InvoicePaidOver, InvoiceWrongAmount,
        InvoiceExpired, InvoiceCancelled, PayoutPending, PayoutApproved, PayoutAwaitingCosign, PayoutBroadcasting,
        PayoutSent, PayoutConfirmed, PayoutFailed, PayoutCancelled, WalletPaid,
    ];

    /// <summary>True when the gateway value is one this snapshot documents.</summary>
    public bool IsKnown => Known.Contains(this);

    /// <summary>Wrap a wire value, known or not.</summary>
    /// <param name="value">The wire value.</param>
    public static EventType FromValue(string value) => new(value);

    /// <summary>The wire value.</summary>
    /// <param name="value">The wrapper.</param>
    public static implicit operator string(EventType value) => value.Value ?? string.Empty;

    /// <summary>
    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let
    /// <c>Status = "padi"</c> compile as a EventType and only fail at the gateway, hours later, on
    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the
    /// gateway added after this snapshot.
    /// </summary>
    /// <param name="value">The wire value.</param>
    public static explicit operator EventType(string value) => new(value);

    /// <inheritdoc />
    public override string ToString() => Value ?? string.Empty;
}

