// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core 2cc44c16f516).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

namespace Oblodai.Contract;

/// <summary>
/// Every error code the gateway can emit (<c>family.reason</c>). The code is the discriminator of
/// the error family: switch on <see cref="OblodaiException.Code"/> against these constants.
/// </summary>
public static class ErrorCodes
{
    /// <summary><c>accepted.no_network</c></summary>
    public const string AcceptedNoNetwork = "accepted.no_network";

    /// <summary><c>accepted.unknown_method</c></summary>
    public const string AcceptedUnknownMethod = "accepted.unknown_method";

    /// <summary><c>accounting.unavailable</c></summary>
    public const string AccountingUnavailable = "accounting.unavailable";

    /// <summary><c>accuracy.out_of_range</c></summary>
    public const string AccuracyOutOfRange = "accuracy.out_of_range";

    /// <summary><c>admin.bad_request</c></summary>
    public const string AdminBadRequest = "admin.bad_request";

    /// <summary><c>admin.disabled</c></summary>
    public const string AdminDisabled = "admin.disabled";

    /// <summary><c>admin.unauthorized</c></summary>
    public const string AdminUnauthorized = "admin.unauthorized";

    /// <summary><c>analytics.bad_time</c></summary>
    public const string AnalyticsBadTime = "analytics.bad_time";

    /// <summary><c>apiallow.bad_cidr</c></summary>
    public const string ApiallowBadCidr = "apiallow.bad_cidr";

    /// <summary><c>apiallow.empty</c></summary>
    public const string ApiallowEmpty = "apiallow.empty";

    /// <summary><c>apiallow.last_entry</c></summary>
    public const string ApiallowLastEntry = "apiallow.last_entry";

    /// <summary><c>apiallow.platform_unidentifiable</c></summary>
    public const string ApiallowPlatformUnidentifiable = "apiallow.platform_unidentifiable";

    /// <summary><c>apiallow.too_many</c></summary>
    public const string ApiallowTooMany = "apiallow.too_many";

    /// <summary><c>auth.bad_timestamp</c></summary>
    public const string AuthBadTimestamp = "auth.bad_timestamp";

    /// <summary><c>auth.body_too_large</c></summary>
    public const string AuthBodyTooLarge = "auth.body_too_large";

    /// <summary><c>auth.ip_not_allowed</c></summary>
    public const string AuthIpNotAllowed = "auth.ip_not_allowed";

    /// <summary><c>autopilot.bad_energy</c></summary>
    public const string AutopilotBadEnergy = "autopilot.bad_energy";

    /// <summary><c>autopilot.bad_usd</c></summary>
    public const string AutopilotBadUsd = "autopilot.bad_usd";

    /// <summary><c>autopilot.energy_no_free_trx</c></summary>
    public const string AutopilotEnergyNoFreeTrx = "autopilot.energy_no_free_trx";

    /// <summary><c>autopilot.energy_too_large</c></summary>
    public const string AutopilotEnergyTooLarge = "autopilot.energy_too_large";

    /// <summary><c>autopilot.freeze_unknown</c></summary>
    public const string AutopilotFreezeUnknown = "autopilot.freeze_unknown";

    /// <summary><c>autopilot.frozen</c></summary>
    public const string AutopilotFrozen = "autopilot.frozen";

    /// <summary><c>autopilot.gas_deep_deficit</c></summary>
    public const string AutopilotGasDeepDeficit = "autopilot.gas_deep_deficit";

    /// <summary><c>autopilot.gas_target_below_min</c></summary>
    public const string AutopilotGasTargetBelowMin = "autopilot.gas_target_below_min";

    /// <summary><c>autopilot.usd_too_large</c></summary>
    public const string AutopilotUsdTooLarge = "autopilot.usd_too_large";

    /// <summary><c>autowithdraw.bad_min</c></summary>
    public const string AutowithdrawBadMin = "autowithdraw.bad_min";

    /// <summary><c>autowithdraw.missing</c></summary>
    public const string AutowithdrawMissing = "autowithdraw.missing";

    /// <summary><c>batch.bad_id</c></summary>
    public const string BatchBadId = "batch.bad_id";

    /// <summary><c>batch.bad_recipient</c></summary>
    public const string BatchBadRecipient = "batch.bad_recipient";

    /// <summary><c>batch.disabled</c></summary>
    public const string BatchDisabled = "batch.disabled";

    /// <summary><c>batch.duplicate_order_id</c></summary>
    public const string BatchDuplicateOrderId = "batch.duplicate_order_id";

    /// <summary><c>batch.duplicate_reference</c></summary>
    public const string BatchDuplicateReference = "batch.duplicate_reference";

    /// <summary><c>batch.empty</c></summary>
    public const string BatchEmpty = "batch.empty";

    /// <summary><c>batch.invoice_required</c></summary>
    public const string BatchInvoiceRequired = "batch.invoice_required";

    /// <summary><c>batch.not_found</c></summary>
    public const string BatchNotFound = "batch.not_found";

    /// <summary><c>batch.order_id_required</c></summary>
    public const string BatchOrderIdRequired = "batch.order_id_required";

    /// <summary><c>batch.reference_required</c></summary>
    public const string BatchReferenceRequired = "batch.reference_required";

    /// <summary><c>batch.too_large</c></summary>
    public const string BatchTooLarge = "batch.too_large";

    /// <summary><c>batch.unsupported_kind</c></summary>
    public const string BatchUnsupportedKind = "batch.unsupported_kind";

    /// <summary><c>blocklist.invalid_address</c></summary>
    public const string BlocklistInvalidAddress = "blocklist.invalid_address";

    /// <summary><c>blocklist.missing_fields</c></summary>
    public const string BlocklistMissingFields = "blocklist.missing_fields";

    /// <summary><c>blocklist.unknown_network</c></summary>
    public const string BlocklistUnknownNetwork = "blocklist.unknown_network";

    /// <summary><c>cheque.token_required</c></summary>
    public const string ChequeTokenRequired = "cheque.token_required";

    /// <summary><c>commission.bad_merchant</c></summary>
    public const string CommissionBadMerchant = "commission.bad_merchant";

    /// <summary><c>commission.fixed_out_of_range</c></summary>
    public const string CommissionFixedOutOfRange = "commission.fixed_out_of_range";

    /// <summary><c>commission.out_of_range</c></summary>
    public const string CommissionOutOfRange = "commission.out_of_range";

    /// <summary><c>compliance.blocked</c></summary>
    public const string ComplianceBlocked = "compliance.blocked";

    /// <summary><c>compliance.blocked_address</c></summary>
    public const string ComplianceBlockedAddress = "compliance.blocked_address";

    /// <summary><c>compliance.blocklist_unavailable</c></summary>
    public const string ComplianceBlocklistUnavailable = "compliance.blocklist_unavailable";

    /// <summary><c>compliance.no_destination</c></summary>
    public const string ComplianceNoDestination = "compliance.no_destination";

    /// <summary><c>compliance.no_network</c></summary>
    public const string ComplianceNoNetwork = "compliance.no_network";

    /// <summary><c>confirmations.bad_tier</c></summary>
    public const string ConfirmationsBadTier = "confirmations.bad_tier";

    /// <summary><c>confirmations.no_network</c></summary>
    public const string ConfirmationsNoNetwork = "confirmations.no_network";

    /// <summary><c>confirmations.tier_too_large</c></summary>
    public const string ConfirmationsTierTooLarge = "confirmations.tier_too_large";

    /// <summary><c>db.unavailable</c></summary>
    public const string DbUnavailable = "db.unavailable";

    /// <summary><c>deposit.generation_stale</c></summary>
    public const string DepositGenerationStale = "deposit.generation_stale";

    /// <summary><c>discount.out_of_range</c></summary>
    public const string DiscountOutOfRange = "discount.out_of_range";

    /// <summary><c>document.bad_format</c></summary>
    public const string DocumentBadFormat = "document.bad_format";

    /// <summary><c>document.bad_id</c></summary>
    public const string DocumentBadId = "document.bad_id";

    /// <summary><c>document.bad_job_id</c></summary>
    public const string DocumentBadJobId = "document.bad_job_id";

    /// <summary><c>document.bad_kind</c></summary>
    public const string DocumentBadKind = "document.bad_kind";

    /// <summary><c>document.bad_signature</c></summary>
    public const string DocumentBadSignature = "document.bad_signature";

    /// <summary><c>document.balance_unavailable</c></summary>
    public const string DocumentBalanceUnavailable = "document.balance_unavailable";

    /// <summary><c>document.batch_unavailable</c></summary>
    public const string DocumentBatchUnavailable = "document.batch_unavailable";

    /// <summary><c>document.daily_quota</c></summary>
    public const string DocumentDailyQuota = "document.daily_quota";

    /// <summary><c>document.disabled</c></summary>
    public const string DocumentDisabled = "document.disabled";

    /// <summary><c>document.encode_failed</c></summary>
    public const string DocumentEncodeFailed = "document.encode_failed";

    /// <summary><c>document.fees_unavailable</c></summary>
    public const string DocumentFeesUnavailable = "document.fees_unavailable";

    /// <summary><c>document.job_expired</c></summary>
    public const string DocumentJobExpired = "document.job_expired";

    /// <summary><c>document.job_failed</c></summary>
    public const string DocumentJobFailed = "document.job_failed";

    /// <summary><c>document.job_not_found</c></summary>
    public const string DocumentJobNotFound = "document.job_not_found";

    /// <summary><c>document.job_not_ready</c></summary>
    public const string DocumentJobNotReady = "document.job_not_ready";

    /// <summary><c>document.jobs_disabled</c></summary>
    public const string DocumentJobsDisabled = "document.jobs_disabled";

    /// <summary><c>document.ledger_unavailable</c></summary>
    public const string DocumentLedgerUnavailable = "document.ledger_unavailable";

    /// <summary><c>document.link_expired</c></summary>
    public const string DocumentLinkExpired = "document.link_expired";

    /// <summary><c>document.no_split</c></summary>
    public const string DocumentNoSplit = "document.no_split";

    /// <summary><c>document.not_found</c></summary>
    public const string DocumentNotFound = "document.not_found";

    /// <summary><c>document.render_failed</c></summary>
    public const string DocumentRenderFailed = "document.render_failed";

    /// <summary><c>document.render_rejected</c></summary>
    public const string DocumentRenderRejected = "document.render_rejected";

    /// <summary><c>document.render_unavailable</c></summary>
    public const string DocumentRenderUnavailable = "document.render_unavailable";

    /// <summary><c>document.too_many_jobs</c></summary>
    public const string DocumentTooManyJobs = "document.too_many_jobs";

    /// <summary><c>document.unknown_kind</c></summary>
    public const string DocumentUnknownKind = "document.unknown_kind";

    /// <summary><c>document.unknown_lang</c></summary>
    public const string DocumentUnknownLang = "document.unknown_lang";

    /// <summary><c>document.wallet_abandoned</c></summary>
    public const string DocumentWalletAbandoned = "document.wallet_abandoned";

    /// <summary><c>document.wallet_blocked</c></summary>
    public const string DocumentWalletBlocked = "document.wallet_blocked";

    /// <summary><c>email.bad_recipient</c></summary>
    public const string EmailBadRecipient = "email.bad_recipient";

    /// <summary><c>email.disabled</c></summary>
    public const string EmailDisabled = "email.disabled";

    /// <summary><c>email.no_recipient</c></summary>
    public const string EmailNoRecipient = "email.no_recipient";

    /// <summary><c>email.rate_limited</c></summary>
    public const string EmailRateLimited = "email.rate_limited";

    /// <summary><c>history.bad_merchant_id</c></summary>
    public const string HistoryBadMerchantId = "history.bad_merchant_id";

    /// <summary><c>idempotency.bad_key</c></summary>
    public const string IdempotencyBadKey = "idempotency.bad_key";

    /// <summary><c>idempotency.in_progress</c></summary>
    public const string IdempotencyInProgress = "idempotency.in_progress";

    /// <summary><c>idempotency.key_reused</c></summary>
    public const string IdempotencyKeyReused = "idempotency.key_reused";

    /// <summary><c>idempotency.unavailable</c></summary>
    public const string IdempotencyUnavailable = "idempotency.unavailable";

    /// <summary><c>internal</c></summary>
    public const string Internal = "internal";

    /// <summary><c>invoice.address_failed</c></summary>
    public const string InvoiceAddressFailed = "invoice.address_failed";

    /// <summary><c>invoice.already_paid</c></summary>
    public const string InvoiceAlreadyPaid = "invoice.already_paid";

    /// <summary><c>invoice.bad_deposit</c></summary>
    public const string InvoiceBadDeposit = "invoice.bad_deposit";

    /// <summary><c>invoice.bad_id</c></summary>
    public const string InvoiceBadId = "invoice.bad_id";

    /// <summary><c>invoice.bad_price</c></summary>
    public const string InvoiceBadPrice = "invoice.bad_price";

    /// <summary><c>invoice.bad_reversal_amount</c></summary>
    public const string InvoiceBadReversalAmount = "invoice.bad_reversal_amount";

    /// <summary><c>invoice.deposit_asset_mismatch</c></summary>
    public const string InvoiceDepositAssetMismatch = "invoice.deposit_asset_mismatch";

    /// <summary><c>invoice.deposit_exists</c></summary>
    public const string InvoiceDepositExists = "invoice.deposit_exists";

    /// <summary><c>invoice.deposit_pending</c></summary>
    public const string InvoiceDepositPending = "invoice.deposit_pending";

    /// <summary><c>invoice.expired</c></summary>
    public const string InvoiceExpired = "invoice.expired";

    /// <summary><c>invoice.fiat_pay_asset</c></summary>
    public const string InvoiceFiatPayAsset = "invoice.fiat_pay_asset";

    /// <summary><c>invoice.generation_stale</c></summary>
    public const string InvoiceGenerationStale = "invoice.generation_stale";

    /// <summary><c>invoice.no_pay_asset</c></summary>
    public const string InvoiceNoPayAsset = "invoice.no_pay_asset";

    /// <summary><c>invoice.no_user</c></summary>
    public const string InvoiceNoUser = "invoice.no_user";

    /// <summary><c>invoice.not_payable</c></summary>
    public const string InvoiceNotPayable = "invoice.not_payable";

    /// <summary><c>invoice.not_selectable</c></summary>
    public const string InvoiceNotSelectable = "invoice.not_selectable";

    /// <summary><c>invoice.nothing_due</c></summary>
    public const string InvoiceNothingDue = "invoice.nothing_due";

    /// <summary><c>invoice.partially_paid</c></summary>
    public const string InvoicePartiallyPaid = "invoice.partially_paid";

    /// <summary><c>invoice.pay_asset_not_selected</c></summary>
    public const string InvoicePayAssetNotSelected = "invoice.pay_asset_not_selected";

    /// <summary><c>invoice.quote_failed</c></summary>
    public const string InvoiceQuoteFailed = "invoice.quote_failed";

    /// <summary><c>invoice.refresh_lease</c></summary>
    public const string InvoiceRefreshLease = "invoice.refresh_lease";

    /// <summary><c>invoice.refresh_not_expired</c></summary>
    public const string InvoiceRefreshNotExpired = "invoice.refresh_not_expired";

    /// <summary><c>invoice.refresh_paid</c></summary>
    public const string InvoiceRefreshPaid = "invoice.refresh_paid";

    /// <summary><c>invoice.refresh_select</c></summary>
    public const string InvoiceRefreshSelect = "invoice.refresh_select";

    /// <summary><c>killswitch.reason_required</c></summary>
    public const string KillswitchReasonRequired = "killswitch.reason_required";

    /// <summary><c>killswitch.unavailable</c></summary>
    public const string KillswitchUnavailable = "killswitch.unavailable";

    /// <summary><c>ledger.asset_mismatch</c></summary>
    public const string LedgerAssetMismatch = "ledger.asset_mismatch";

    /// <summary><c>ledger.idempotency_conflict</c></summary>
    public const string LedgerIdempotencyConflict = "ledger.idempotency_conflict";

    /// <summary><c>ledger.sandbox_live_mix</c></summary>
    public const string LedgerSandboxLiveMix = "ledger.sandbox_live_mix";

    /// <summary><c>ledger.unavailable</c></summary>
    public const string LedgerUnavailable = "ledger.unavailable";

    /// <summary><c>merchant.already_sandbox</c></summary>
    public const string MerchantAlreadySandbox = "merchant.already_sandbox";

    /// <summary><c>merchant.bad_fee_bearer</c></summary>
    public const string MerchantBadFeeBearer = "merchant.bad_fee_bearer";

    /// <summary><c>merchant.bad_id</c></summary>
    public const string MerchantBadId = "merchant.bad_id";

    /// <summary><c>merchant.bad_project_id</c></summary>
    public const string MerchantBadProjectId = "merchant.bad_project_id";

    /// <summary><c>merchant.bad_settles_to</c></summary>
    public const string MerchantBadSettlesTo = "merchant.bad_settles_to";

    /// <summary><c>merchant.bad_signature</c></summary>
    public const string MerchantBadSignature = "merchant.bad_signature";

    /// <summary><c>merchant.bad_subtract</c></summary>
    public const string MerchantBadSubtract = "merchant.bad_subtract";

    /// <summary><c>merchant.close_unavailable</c></summary>
    public const string MerchantCloseUnavailable = "merchant.close_unavailable";

    /// <summary><c>merchant.email_required</c></summary>
    public const string MerchantEmailRequired = "merchant.email_required";

    /// <summary><c>merchant.key_mode_mismatch</c></summary>
    public const string MerchantKeyModeMismatch = "merchant.key_mode_mismatch";

    /// <summary><c>merchant.no_owner</c></summary>
    public const string MerchantNoOwner = "merchant.no_owner";

    /// <summary><c>merchant.no_personal_wallet</c></summary>
    public const string MerchantNoPersonalWallet = "merchant.no_personal_wallet";

    /// <summary><c>merchant.not_found</c></summary>
    public const string MerchantNotFound = "merchant.not_found";

    /// <summary><c>merchant.project_mismatch</c></summary>
    public const string MerchantProjectMismatch = "merchant.project_mismatch";

    /// <summary><c>merchant.secret_decrypt</c></summary>
    public const string MerchantSecretDecrypt = "merchant.secret_decrypt";

    /// <summary><c>merchant.unknown_key</c></summary>
    public const string MerchantUnknownKey = "merchant.unknown_key";

    /// <summary><c>minimum.negative</c></summary>
    public const string MinimumNegative = "minimum.negative";

    /// <summary><c>minimum.no_network</c></summary>
    public const string MinimumNoNetwork = "minimum.no_network";

    /// <summary><c>onramp.admit</c></summary>
    public const string OnrampAdmit = "onramp.admit";

    /// <summary><c>onramp.advance</c></summary>
    public const string OnrampAdvance = "onramp.advance";

    /// <summary><c>onramp.already_delivered</c></summary>
    public const string OnrampAlreadyDelivered = "onramp.already_delivered";

    /// <summary><c>onramp.bad_invoice</c></summary>
    public const string OnrampBadInvoice = "onramp.bad_invoice";

    /// <summary><c>onramp.bad_status</c></summary>
    public const string OnrampBadStatus = "onramp.bad_status";

    /// <summary><c>onramp.captured</c></summary>
    public const string OnrampCaptured = "onramp.captured";

    /// <summary><c>onramp.expire</c></summary>
    public const string OnrampExpire = "onramp.expire";

    /// <summary><c>onramp.fail_captured</c></summary>
    public const string OnrampFailCaptured = "onramp.fail_captured";

    /// <summary><c>onramp.for_invoice</c></summary>
    public const string OnrampForInvoice = "onramp.for_invoice";

    /// <summary><c>onramp.force_completed</c></summary>
    public const string OnrampForceCompleted = "onramp.force_completed";

    /// <summary><c>onramp.invoice_not_found</c></summary>
    public const string OnrampInvoiceNotFound = "onramp.invoice_not_found";

    /// <summary><c>onramp.invoice_not_payable</c></summary>
    public const string OnrampInvoiceNotPayable = "onramp.invoice_not_payable";

    /// <summary><c>onramp.money_already_landed</c></summary>
    public const string OnrampMoneyAlreadyLanded = "onramp.money_already_landed";

    /// <summary><c>onramp.no_evidence</c></summary>
    public const string OnrampNoEvidence = "onramp.no_evidence";

    /// <summary><c>onramp.no_refund_evidence</c></summary>
    public const string OnrampNoRefundEvidence = "onramp.no_refund_evidence";

    /// <summary><c>onramp.not_captured</c></summary>
    public const string OnrampNotCaptured = "onramp.not_captured";

    /// <summary><c>onramp.not_found</c></summary>
    public const string OnrampNotFound = "onramp.not_found";

    /// <summary><c>onramp.open</c></summary>
    public const string OnrampOpen = "onramp.open";

    /// <summary><c>onramp.open_conflict</c></summary>
    public const string OnrampOpenConflict = "onramp.open_conflict";

    /// <summary><c>onramp.overdue</c></summary>
    public const string OnrampOverdue = "onramp.overdue";

    /// <summary><c>onramp.owner_required</c></summary>
    public const string OnrampOwnerRequired = "onramp.owner_required";

    /// <summary><c>onramp.refund_evidence</c></summary>
    public const string OnrampRefundEvidence = "onramp.refund_evidence";

    /// <summary><c>onramp.release</c></summary>
    public const string OnrampRelease = "onramp.release";

    /// <summary><c>onramp.suppressed_in</c></summary>
    public const string OnrampSuppressedIn = "onramp.suppressed_in";

    /// <summary><c>onramp.suppresses</c></summary>
    public const string OnrampSuppresses = "onramp.suppresses";

    /// <summary><c>onramp.target_required</c></summary>
    public const string OnrampTargetRequired = "onramp.target_required";

    /// <summary><c>onramp.terminal</c></summary>
    public const string OnrampTerminal = "onramp.terminal";

    /// <summary><c>onramp.token</c></summary>
    public const string OnrampToken = "onramp.token";

    /// <summary><c>pay.bad_uuid</c></summary>
    public const string PayBadUuid = "pay.bad_uuid";

    /// <summary><c>pay.below_minimum</c></summary>
    public const string PayBelowMinimum = "pay.below_minimum";

    /// <summary><c>pay.discount_unavailable</c></summary>
    public const string PayDiscountUnavailable = "pay.discount_unavailable";

    /// <summary><c>pay.method_not_accepted</c></summary>
    public const string PayMethodNotAccepted = "pay.method_not_accepted";

    /// <summary><c>pay.minimum_unavailable</c></summary>
    public const string PayMinimumUnavailable = "pay.minimum_unavailable";

    /// <summary><c>pay.not_selectable</c></summary>
    public const string PayNotSelectable = "pay.not_selectable";

    /// <summary><c>paylink.above_max</c></summary>
    public const string PaylinkAboveMax = "paylink.above_max";

    /// <summary><c>paylink.amount_required</c></summary>
    public const string PaylinkAmountRequired = "paylink.amount_required";

    /// <summary><c>paylink.bad_amount</c></summary>
    public const string PaylinkBadAmount = "paylink.bad_amount";

    /// <summary><c>paylink.bad_bounds</c></summary>
    public const string PaylinkBadBounds = "paylink.bad_bounds";

    /// <summary><c>paylink.bad_id</c></summary>
    public const string PaylinkBadId = "paylink.bad_id";

    /// <summary><c>paylink.bad_max</c></summary>
    public const string PaylinkBadMax = "paylink.bad_max";

    /// <summary><c>paylink.bad_min</c></summary>
    public const string PaylinkBadMin = "paylink.bad_min";

    /// <summary><c>paylink.bad_mode</c></summary>
    public const string PaylinkBadMode = "paylink.bad_mode";

    /// <summary><c>paylink.bad_range</c></summary>
    public const string PaylinkBadRange = "paylink.bad_range";

    /// <summary><c>paylink.below_min</c></summary>
    public const string PaylinkBelowMin = "paylink.below_min";

    /// <summary><c>paylink.disabled</c></summary>
    public const string PaylinkDisabled = "paylink.disabled";

    /// <summary><c>paylink.expires_in_negative</c></summary>
    public const string PaylinkExpiresInNegative = "paylink.expires_in_negative";

    /// <summary><c>paylink.expires_in_too_large</c></summary>
    public const string PaylinkExpiresInTooLarge = "paylink.expires_in_too_large";

    /// <summary><c>paylink.not_found</c></summary>
    public const string PaylinkNotFound = "paylink.not_found";

    /// <summary><c>paylink.not_positive</c></summary>
    public const string PaylinkNotPositive = "paylink.not_positive";

    /// <summary><c>paylink.order_id_invalid</c></summary>
    public const string PaylinkOrderIdInvalid = "paylink.order_id_invalid";

    /// <summary><c>paylink.order_id_too_long</c></summary>
    public const string PaylinkOrderIdTooLong = "paylink.order_id_too_long";

    /// <summary><c>paylink.rate_limited</c></summary>
    public const string PaylinkRateLimited = "paylink.rate_limited";

    /// <summary><c>paylink.unavailable</c></summary>
    public const string PaylinkUnavailable = "paylink.unavailable";

    /// <summary><c>payment.bad_accuracy</c></summary>
    public const string PaymentBadAccuracy = "payment.bad_accuracy";

    /// <summary><c>payment.bad_amount</c></summary>
    public const string PaymentBadAmount = "payment.bad_amount";

    /// <summary><c>payment.bad_payer_email</c></summary>
    public const string PaymentBadPayerEmail = "payment.bad_payer_email";

    /// <summary><c>payment.bad_redirect_url</c></summary>
    public const string PaymentBadRedirectUrl = "payment.bad_redirect_url";

    /// <summary><c>payment.bad_status</c></summary>
    public const string PaymentBadStatus = "payment.bad_status";

    /// <summary><c>payment.bad_subtract</c></summary>
    public const string PaymentBadSubtract = "payment.bad_subtract";

    /// <summary><c>payment.bad_url_callback</c></summary>
    public const string PaymentBadUrlCallback = "payment.bad_url_callback";

    /// <summary><c>payment.bad_uuid</c></summary>
    public const string PaymentBadUuid = "payment.bad_uuid";

    /// <summary><c>payment.below_minimum</c></summary>
    public const string PaymentBelowMinimum = "payment.below_minimum";

    /// <summary><c>payment.discount_unavailable</c></summary>
    public const string PaymentDiscountUnavailable = "payment.discount_unavailable";

    /// <summary><c>payment.minimum_unavailable</c></summary>
    public const string PaymentMinimumUnavailable = "payment.minimum_unavailable";

    /// <summary><c>payment.network_required</c></summary>
    public const string PaymentNetworkRequired = "payment.network_required";

    /// <summary><c>payment.no_lookup</c></summary>
    public const string PaymentNoLookup = "payment.no_lookup";

    /// <summary><c>payment.not_found</c></summary>
    public const string PaymentNotFound = "payment.not_found";

    /// <summary><c>payment.subtract_impossible</c></summary>
    public const string PaymentSubtractImpossible = "payment.subtract_impossible";

    /// <summary><c>payment.to_currency_required</c></summary>
    public const string PaymentToCurrencyRequired = "payment.to_currency_required";

    /// <summary><c>payment.unknown_to_currency</c></summary>
    public const string PaymentUnknownToCurrency = "payment.unknown_to_currency";

    /// <summary><c>payment.unsupported_network</c></summary>
    public const string PaymentUnsupportedNetwork = "payment.unsupported_network";

    /// <summary><c>payout.address_network_mismatch</c></summary>
    public const string PayoutAddressNetworkMismatch = "payout.address_network_mismatch";

    /// <summary><c>payout.amount_below_fee</c></summary>
    public const string PayoutAmountBelowFee = "payout.amount_below_fee";

    /// <summary><c>payout.approver_is_creator</c></summary>
    public const string PayoutApproverIsCreator = "payout.approver_is_creator";

    /// <summary><c>payout.asset_mismatch</c></summary>
    public const string PayoutAssetMismatch = "payout.asset_mismatch";

    /// <summary><c>payout.bad_address</c></summary>
    public const string PayoutBadAddress = "payout.bad_address";

    /// <summary><c>payout.bad_amount</c></summary>
    public const string PayoutBadAmount = "payout.bad_amount";

    /// <summary><c>payout.bad_kind</c></summary>
    public const string PayoutBadKind = "payout.bad_kind";

    /// <summary><c>payout.bad_memo</c></summary>
    public const string PayoutBadMemo = "payout.bad_memo";

    /// <summary><c>payout.bad_owner_kind</c></summary>
    public const string PayoutBadOwnerKind = "payout.bad_owner_kind";

    /// <summary><c>payout.bad_state</c></summary>
    public const string PayoutBadState = "payout.bad_state";

    /// <summary><c>payout.bad_status</c></summary>
    public const string PayoutBadStatus = "payout.bad_status";

    /// <summary><c>payout.bad_url_callback</c></summary>
    public const string PayoutBadUrlCallback = "payout.bad_url_callback";

    /// <summary><c>payout.bad_user</c></summary>
    public const string PayoutBadUser = "payout.bad_user";

    /// <summary><c>payout.bad_uuid</c></summary>
    public const string PayoutBadUuid = "payout.bad_uuid";

    /// <summary><c>payout.batch_too_large</c></summary>
    public const string PayoutBatchTooLarge = "payout.batch_too_large";

    /// <summary><c>payout.broadcast_in_flight</c></summary>
    public const string PayoutBroadcastInFlight = "payout.broadcast_in_flight";

    /// <summary><c>payout.convert_bad_amount</c></summary>
    public const string PayoutConvertBadAmount = "payout.convert_bad_amount";

    /// <summary><c>payout.convert_frozen</c></summary>
    public const string PayoutConvertFrozen = "payout.convert_frozen";

    /// <summary><c>payout.convert_insufficient</c></summary>
    public const string PayoutConvertInsufficient = "payout.convert_insufficient";

    /// <summary><c>payout.convert_no_rate</c></summary>
    public const string PayoutConvertNoRate = "payout.convert_no_rate";

    /// <summary><c>payout.convert_same_asset</c></summary>
    public const string PayoutConvertSameAsset = "payout.convert_same_asset";

    /// <summary><c>payout.convert_unsupported</c></summary>
    public const string PayoutConvertUnsupported = "payout.convert_unsupported";

    /// <summary><c>payout.destination_internal</c></summary>
    public const string PayoutDestinationInternal = "payout.destination_internal";

    /// <summary><c>payout.empty_batch</c></summary>
    public const string PayoutEmptyBatch = "payout.empty_batch";

    /// <summary><c>payout.fee_asset_mismatch</c></summary>
    public const string PayoutFeeAssetMismatch = "payout.fee_asset_mismatch";

    /// <summary><c>payout.freeze_unknown</c></summary>
    public const string PayoutFreezeUnknown = "payout.freeze_unknown";

    /// <summary><c>payout.from_currency_unsupported</c></summary>
    public const string PayoutFromCurrencyUnsupported = "payout.from_currency_unsupported";

    /// <summary><c>payout.frozen</c></summary>
    public const string PayoutFrozen = "payout.frozen";

    /// <summary><c>payout.funds_maturing</c></summary>
    public const string PayoutFundsMaturing = "payout.funds_maturing";

    /// <summary><c>payout.insufficient_funds</c></summary>
    public const string PayoutInsufficientFunds = "payout.insufficient_funds";

    /// <summary><c>payout.memo_conflict</c></summary>
    public const string PayoutMemoConflict = "payout.memo_conflict";

    /// <summary><c>payout.memo_required</c></summary>
    public const string PayoutMemoRequired = "payout.memo_required";

    /// <summary><c>payout.memo_too_long</c></summary>
    public const string PayoutMemoTooLong = "payout.memo_too_long";

    /// <summary><c>payout.no_destination</c></summary>
    public const string PayoutNoDestination = "payout.no_destination";

    /// <summary><c>payout.no_lookup</c></summary>
    public const string PayoutNoLookup = "payout.no_lookup";

    /// <summary><c>payout.no_owner</c></summary>
    public const string PayoutNoOwner = "payout.no_owner";

    /// <summary><c>payout.no_sender</c></summary>
    public const string PayoutNoSender = "payout.no_sender";

    /// <summary><c>payout.no_txid</c></summary>
    public const string PayoutNoTxid = "payout.no_txid";

    /// <summary><c>payout.no_user</c></summary>
    public const string PayoutNoUser = "payout.no_user";

    /// <summary><c>payout.not_broadcasting</c></summary>
    public const string PayoutNotBroadcasting = "payout.not_broadcasting";

    /// <summary><c>payout.not_found</c></summary>
    public const string PayoutNotFound = "payout.not_found";

    /// <summary><c>payout.not_pending</c></summary>
    public const string PayoutNotPending = "payout.not_pending";

    /// <summary><c>payout.not_sent</c></summary>
    public const string PayoutNotSent = "payout.not_sent";

    /// <summary><c>payout.order_id_required</c></summary>
    public const string PayoutOrderIdRequired = "payout.order_id_required";

    /// <summary><c>payout.reference_collision</c></summary>
    public const string PayoutReferenceCollision = "payout.reference_collision";

    /// <summary><c>payout.release_reason_required</c></summary>
    public const string PayoutReleaseReasonRequired = "payout.release_reason_required";

    /// <summary><c>payout.reserved_reference</c></summary>
    public const string PayoutReservedReference = "payout.reserved_reference";

    /// <summary><c>payout.test_merchant</c></summary>
    public const string PayoutTestMerchant = "payout.test_merchant";

    /// <summary><c>payout_link.disabled</c></summary>
    public const string PayoutLinkDisabled = "payout_link.disabled";

    /// <summary><c>payoutctl.bad_body</c></summary>
    public const string PayoutctlBadBody = "payoutctl.bad_body";

    /// <summary><c>payoutctl.bad_cap</c></summary>
    public const string PayoutctlBadCap = "payoutctl.bad_cap";

    /// <summary><c>payoutctl.bad_source</c></summary>
    public const string PayoutctlBadSource = "payoutctl.bad_source";

    /// <summary><c>payoutctl.unavailable</c></summary>
    public const string PayoutctlUnavailable = "payoutctl.unavailable";

    /// <summary><c>payoutlink.already_claimed</c></summary>
    public const string PayoutlinkAlreadyClaimed = "payoutlink.already_claimed";

    /// <summary><c>payoutlink.bad_amount</c></summary>
    public const string PayoutlinkBadAmount = "payoutlink.bad_amount";

    /// <summary><c>payoutlink.bad_fee_bearer</c></summary>
    public const string PayoutlinkBadFeeBearer = "payoutlink.bad_fee_bearer";

    /// <summary><c>payoutlink.bad_id</c></summary>
    public const string PayoutlinkBadId = "payoutlink.bad_id";

    /// <summary><c>payoutlink.bad_passcode</c></summary>
    public const string PayoutlinkBadPasscode = "payoutlink.bad_passcode";

    /// <summary><c>payoutlink.bad_state</c></summary>
    public const string PayoutlinkBadState = "payoutlink.bad_state";

    /// <summary><c>payoutlink.batch_too_large</c></summary>
    public const string PayoutlinkBatchTooLarge = "payoutlink.batch_too_large";

    /// <summary><c>payoutlink.cancelled</c></summary>
    public const string PayoutlinkCancelled = "payoutlink.cancelled";

    /// <summary><c>payoutlink.claim_in_progress</c></summary>
    public const string PayoutlinkClaimInProgress = "payoutlink.claim_in_progress";

    /// <summary><c>payoutlink.destination_internal</c></summary>
    public const string PayoutlinkDestinationInternal = "payoutlink.destination_internal";

    /// <summary><c>payoutlink.disabled</c></summary>
    public const string PayoutlinkDisabled = "payoutlink.disabled";

    /// <summary><c>payoutlink.duplicate_reference</c></summary>
    public const string PayoutlinkDuplicateReference = "payoutlink.duplicate_reference";

    /// <summary><c>payoutlink.empty_batch</c></summary>
    public const string PayoutlinkEmptyBatch = "payoutlink.empty_batch";

    /// <summary><c>payoutlink.expired</c></summary>
    public const string PayoutlinkExpired = "payoutlink.expired";

    /// <summary><c>payoutlink.funds_maturing</c></summary>
    public const string PayoutlinkFundsMaturing = "payoutlink.funds_maturing";

    /// <summary><c>payoutlink.idempotency_required</c></summary>
    public const string PayoutlinkIdempotencyRequired = "payoutlink.idempotency_required";

    /// <summary><c>payoutlink.insufficient_funds</c></summary>
    public const string PayoutlinkInsufficientFunds = "payoutlink.insufficient_funds";

    /// <summary><c>payoutlink.no_address</c></summary>
    public const string PayoutlinkNoAddress = "payoutlink.no_address";

    /// <summary><c>payoutlink.not_found</c></summary>
    public const string PayoutlinkNotFound = "payoutlink.not_found";

    /// <summary><c>payoutlink.not_funded</c></summary>
    public const string PayoutlinkNotFunded = "payoutlink.not_funded";

    /// <summary><c>payoutlink.passcode</c></summary>
    public const string PayoutlinkPasscode = "payoutlink.passcode";

    /// <summary><c>payoutlink.passcode_locked</c></summary>
    public const string PayoutlinkPasscodeLocked = "payoutlink.passcode_locked";

    /// <summary><c>payoutlink.passcode_required</c></summary>
    public const string PayoutlinkPasscodeRequired = "payoutlink.passcode_required";

    /// <summary><c>payoutlink.passcode_wrong</c></summary>
    public const string PayoutlinkPasscodeWrong = "payoutlink.passcode_wrong";

    /// <summary><c>payoutlink.reference_required</c></summary>
    public const string PayoutlinkReferenceRequired = "payoutlink.reference_required";

    /// <summary><c>payoutlink.token</c></summary>
    public const string PayoutlinkToken = "payoutlink.token";

    /// <summary><c>payoutlink.unavailable</c></summary>
    public const string PayoutlinkUnavailable = "payoutlink.unavailable";

    /// <summary><c>payoutlink.unsupported_network</c></summary>
    public const string PayoutlinkUnsupportedNetwork = "payoutlink.unsupported_network";

    /// <summary><c>personal.amount_invalid</c></summary>
    public const string PersonalAmountInvalid = "personal.amount_invalid";

    /// <summary><c>personal.amount_too_small</c></summary>
    public const string PersonalAmountTooSmall = "personal.amount_too_small";

    /// <summary><c>personal.asset_mismatch</c></summary>
    public const string PersonalAssetMismatch = "personal.asset_mismatch";

    /// <summary><c>personal.bad_amount</c></summary>
    public const string PersonalBadAmount = "personal.bad_amount";

    /// <summary><c>personal.bad_deposit_id</c></summary>
    public const string PersonalBadDepositId = "personal.bad_deposit_id";

    /// <summary><c>personal.bad_fund_id</c></summary>
    public const string PersonalBadFundId = "personal.bad_fund_id";

    /// <summary><c>personal.bad_hold_amount</c></summary>
    public const string PersonalBadHoldAmount = "personal.bad_hold_amount";

    /// <summary><c>personal.bad_hold_id</c></summary>
    public const string PersonalBadHoldId = "personal.bad_hold_id";

    /// <summary><c>personal.bad_source</c></summary>
    public const string PersonalBadSource = "personal.bad_source";

    /// <summary><c>personal.bad_source_id</c></summary>
    public const string PersonalBadSourceId = "personal.bad_source_id";

    /// <summary><c>personal.bad_stake_amount</c></summary>
    public const string PersonalBadStakeAmount = "personal.bad_stake_amount";

    /// <summary><c>personal.conversions_frozen</c></summary>
    public const string PersonalConversionsFrozen = "personal.conversions_frozen";

    /// <summary><c>personal.convert_unsupported</c></summary>
    public const string PersonalConvertUnsupported = "personal.convert_unsupported";

    /// <summary><c>personal.funds_maturing</c></summary>
    public const string PersonalFundsMaturing = "personal.funds_maturing";

    /// <summary><c>personal.hold_claimed</c></summary>
    public const string PersonalHoldClaimed = "personal.hold_claimed";

    /// <summary><c>personal.hold_idem_reuse</c></summary>
    public const string PersonalHoldIdemReuse = "personal.hold_idem_reuse";

    /// <summary><c>personal.hold_kind</c></summary>
    public const string PersonalHoldKind = "personal.hold_kind";

    /// <summary><c>personal.hold_no_recipient</c></summary>
    public const string PersonalHoldNoRecipient = "personal.hold_no_recipient";

    /// <summary><c>personal.hold_not_found</c></summary>
    public const string PersonalHoldNotFound = "personal.hold_not_found";

    /// <summary><c>personal.hold_settled</c></summary>
    public const string PersonalHoldSettled = "personal.hold_settled";

    /// <summary><c>personal.idempotency_conflict</c></summary>
    public const string PersonalIdempotencyConflict = "personal.idempotency_conflict";

    /// <summary><c>personal.insufficient</c></summary>
    public const string PersonalInsufficient = "personal.insufficient";

    /// <summary><c>personal.interest_excessive</c></summary>
    public const string PersonalInterestExcessive = "personal.interest_excessive";

    /// <summary><c>personal.no_idem</c></summary>
    public const string PersonalNoIdem = "personal.no_idem";

    /// <summary><c>personal.no_recipient</c></summary>
    public const string PersonalNoRecipient = "personal.no_recipient";

    /// <summary><c>personal.no_user</c></summary>
    public const string PersonalNoUser = "personal.no_user";

    /// <summary><c>personal.recipient_not_found</c></summary>
    public const string PersonalRecipientNotFound = "personal.recipient_not_found";

    /// <summary><c>personal.self_transfer</c></summary>
    public const string PersonalSelfTransfer = "personal.self_transfer";

    /// <summary><c>personal.stake_not_found</c></summary>
    public const string PersonalStakeNotFound = "personal.stake_not_found";

    /// <summary><c>postgres.lock_pool_busy</c></summary>
    public const string PostgresLockPoolBusy = "postgres.lock_pool_busy";

    /// <summary><c>qr.no_address</c></summary>
    public const string QrNoAddress = "qr.no_address";

    /// <summary><c>quarantine.bad_amount</c></summary>
    public const string QuarantineBadAmount = "quarantine.bad_amount";

    /// <summary><c>quarantine.credit_reversed</c></summary>
    public const string QuarantineCreditReversed = "quarantine.credit_reversed";

    /// <summary><c>quarantine.not_open</c></summary>
    public const string QuarantineNotOpen = "quarantine.not_open";

    /// <summary><c>quarantine.test_merchant</c></summary>
    public const string QuarantineTestMerchant = "quarantine.test_merchant";

    /// <summary><c>quarantine.unknown_asset</c></summary>
    public const string QuarantineUnknownAsset = "quarantine.unknown_asset";

    /// <summary><c>quarantine.unknown_merchant</c></summary>
    public const string QuarantineUnknownMerchant = "quarantine.unknown_merchant";

    /// <summary><c>rate.unavailable</c></summary>
    public const string RateUnavailable = "rate.unavailable";

    /// <summary><c>rates.deviation</c></summary>
    public const string RatesDeviation = "rates.deviation";

    /// <summary><c>rates.fiat_pay_asset</c></summary>
    public const string RatesFiatPayAsset = "rates.fiat_pay_asset";

    /// <summary><c>rates.no_pay_asset</c></summary>
    public const string RatesNoPayAsset = "rates.no_pay_asset";

    /// <summary><c>rates.no_source</c></summary>
    public const string RatesNoSource = "rates.no_source";

    /// <summary><c>rates.non_positive</c></summary>
    public const string RatesNonPositive = "rates.non_positive";

    /// <summary><c>rates.stale_rate</c></summary>
    public const string RatesStaleRate = "rates.stale_rate";

    /// <summary><c>rates.unavailable</c></summary>
    public const string RatesUnavailable = "rates.unavailable";

    /// <summary><c>referral.disabled</c></summary>
    public const string ReferralDisabled = "referral.disabled";

    /// <summary><c>referral.no_code</c></summary>
    public const string ReferralNoCode = "referral.no_code";

    /// <summary><c>referral.no_tiers</c></summary>
    public const string ReferralNoTiers = "referral.no_tiers";

    /// <summary><c>referral.out_of_range</c></summary>
    public const string ReferralOutOfRange = "referral.out_of_range";

    /// <summary><c>refund.bad_amount</c></summary>
    public const string RefundBadAmount = "refund.bad_amount";

    /// <summary><c>refund.chain_ambiguous</c></summary>
    public const string RefundChainAmbiguous = "refund.chain_ambiguous";

    /// <summary><c>refund.destination_internal</c></summary>
    public const string RefundDestinationInternal = "refund.destination_internal";

    /// <summary><c>refund.dust</c></summary>
    public const string RefundDust = "refund.dust";

    /// <summary><c>refund.exceeds_excess</c></summary>
    public const string RefundExceedsExcess = "refund.exceeds_excess";

    /// <summary><c>refund.exceeds_refundable</c></summary>
    public const string RefundExceedsRefundable = "refund.exceeds_refundable";

    /// <summary><c>refund.fence_check</c></summary>
    public const string RefundFenceCheck = "refund.fence_check";

    /// <summary><c>refund.no_address</c></summary>
    public const string RefundNoAddress = "refund.no_address";

    /// <summary><c>refund.nothing_to_refund</c></summary>
    public const string RefundNothingToRefund = "refund.nothing_to_refund";

    /// <summary><c>refund.paid_internally</c></summary>
    public const string RefundPaidInternally = "refund.paid_internally";

    /// <summary><c>refund.reference_collision</c></summary>
    public const string RefundReferenceCollision = "refund.reference_collision";

    /// <summary><c>refund.too_many_attempts</c></summary>
    public const string RefundTooManyAttempts = "refund.too_many_attempts";

    /// <summary><c>report.too_large</c></summary>
    public const string ReportTooLarge = "report.too_large";

    /// <summary><c>request.bad_id</c></summary>
    public const string RequestBadId = "request.bad_id";

    /// <summary><c>request.bad_json</c></summary>
    public const string RequestBadJson = "request.bad_json";

    /// <summary><c>request.body_read</c></summary>
    public const string RequestBodyRead = "request.body_read";

    /// <summary><c>request.conflicting_field</c></summary>
    public const string RequestConflictingField = "request.conflicting_field";

    /// <summary><c>request.control_char</c></summary>
    public const string RequestControlChar = "request.control_char";

    /// <summary><c>request.duplicate_field</c></summary>
    public const string RequestDuplicateField = "request.duplicate_field";

    /// <summary><c>request.method_not_allowed</c></summary>
    public const string RequestMethodNotAllowed = "request.method_not_allowed";

    /// <summary><c>request.missing_field</c></summary>
    public const string RequestMissingField = "request.missing_field";

    /// <summary><c>request.not_found</c></summary>
    public const string RequestNotFound = "request.not_found";

    /// <summary><c>request.nul_byte</c></summary>
    public const string RequestNulByte = "request.nul_byte";

    /// <summary><c>request.rate_limited</c></summary>
    public const string RequestRateLimited = "request.rate_limited";

    /// <summary><c>request.reference_invalid</c></summary>
    public const string RequestReferenceInvalid = "request.reference_invalid";

    /// <summary><c>request.reference_too_long</c></summary>
    public const string RequestReferenceTooLong = "request.reference_too_long";

    /// <summary><c>request.too_deep</c></summary>
    public const string RequestTooDeep = "request.too_deep";

    /// <summary><c>request.unknown_currency</c></summary>
    public const string RequestUnknownCurrency = "request.unknown_currency";

    /// <summary><c>request.unreadable</c></summary>
    public const string RequestUnreadable = "request.unreadable";

    /// <summary><c>resolution.already_refunded</c></summary>
    public const string ResolutionAlreadyRefunded = "resolution.already_refunded";

    /// <summary><c>resolution.already_resolved</c></summary>
    public const string ResolutionAlreadyResolved = "resolution.already_resolved";

    /// <summary><c>resolution.bad_action</c></summary>
    public const string ResolutionBadAction = "resolution.bad_action";

    /// <summary><c>resolution.chain_ambiguous</c></summary>
    public const string ResolutionChainAmbiguous = "resolution.chain_ambiguous";

    /// <summary><c>resolution.disabled</c></summary>
    public const string ResolutionDisabled = "resolution.disabled";

    /// <summary><c>resolution.not_underpaid</c></summary>
    public const string ResolutionNotUnderpaid = "resolution.not_underpaid";

    /// <summary><c>routing.awaiting_settle</c></summary>
    public const string RoutingAwaitingSettle = "routing.awaiting_settle";

    /// <summary><c>routing.onramp_check_failed</c></summary>
    public const string RoutingOnrampCheckFailed = "routing.onramp_check_failed";

    /// <summary><c>routing.refund_in_flight</c></summary>
    public const string RoutingRefundInFlight = "routing.refund_in_flight";

    /// <summary><c>routing.refund_payer_unresolved</c></summary>
    public const string RoutingRefundPayerUnresolved = "routing.refund_payer_unresolved";

    /// <summary><c>routing.share_payout_check_failed</c></summary>
    public const string RoutingSharePayoutCheckFailed = "routing.share_payout_check_failed";

    /// <summary><c>routing.share_reattempts_exhausted</c></summary>
    public const string RoutingShareReattemptsExhausted = "routing.share_reattempts_exhausted";

    /// <summary><c>routing.underpay_unresolved</c></summary>
    public const string RoutingUnderpayUnresolved = "routing.underpay_unresolved";

    /// <summary><c>sandbox.amount_too_large</c></summary>
    public const string SandboxAmountTooLarge = "sandbox.amount_too_large";

    /// <summary><c>sandbox.bad_amount</c></summary>
    public const string SandboxBadAmount = "sandbox.bad_amount";

    /// <summary><c>sandbox.bad_asset</c></summary>
    public const string SandboxBadAsset = "sandbox.bad_asset";

    /// <summary><c>sandbox.bad_delivery</c></summary>
    public const string SandboxBadDelivery = "sandbox.bad_delivery";

    /// <summary><c>sandbox.bad_invoice</c></summary>
    public const string SandboxBadInvoice = "sandbox.bad_invoice";

    /// <summary><c>sandbox.convert_not_available</c></summary>
    public const string SandboxConvertNotAvailable = "sandbox.convert_not_available";

    /// <summary><c>sandbox.delivery_not_found</c></summary>
    public const string SandboxDeliveryNotFound = "sandbox.delivery_not_found";

    /// <summary><c>sandbox.invoice_not_found</c></summary>
    public const string SandboxInvoiceNotFound = "sandbox.invoice_not_found";

    /// <summary><c>sandbox.live_key</c></summary>
    public const string SandboxLiveKey = "sandbox.live_key";

    /// <summary><c>sandbox.transfer_not_available</c></summary>
    public const string SandboxTransferNotAvailable = "sandbox.transfer_not_available";

    /// <summary><c>split.bad_destination</c></summary>
    public const string SplitBadDestination = "split.bad_destination";

    /// <summary><c>split.bad_hold</c></summary>
    public const string SplitBadHold = "split.bad_hold";

    /// <summary><c>split.bad_id</c></summary>
    public const string SplitBadId = "split.bad_id";

    /// <summary><c>split.bad_merchant</c></summary>
    public const string SplitBadMerchant = "split.bad_merchant";

    /// <summary><c>split.bad_percent</c></summary>
    public const string SplitBadPercent = "split.bad_percent";

    /// <summary><c>split.bad_reversal_claim</c></summary>
    public const string SplitBadReversalClaim = "split.bad_reversal_claim";

    /// <summary><c>split.consent_check_failed</c></summary>
    public const string SplitConsentCheckFailed = "split.consent_check_failed";

    /// <summary><c>split.dest_check_failed</c></summary>
    public const string SplitDestCheckFailed = "split.dest_check_failed";

    /// <summary><c>split.dest_not_found</c></summary>
    public const string SplitDestNotFound = "split.dest_not_found";

    /// <summary><c>split.disabled</c></summary>
    public const string SplitDisabled = "split.disabled";

    /// <summary><c>split.duplicate_destination</c></summary>
    public const string SplitDuplicateDestination = "split.duplicate_destination";

    /// <summary><c>split.network_required</c></summary>
    public const string SplitNetworkRequired = "split.network_required";

    /// <summary><c>split.not_found</c></summary>
    public const string SplitNotFound = "split.not_found";

    /// <summary><c>split.recipient_not_opted_in</c></summary>
    public const string SplitRecipientNotOptedIn = "split.recipient_not_opted_in";

    /// <summary><c>split.self_destination</c></summary>
    public const string SplitSelfDestination = "split.self_destination";

    /// <summary><c>statement.bad_from</c></summary>
    public const string StatementBadFrom = "statement.bad_from";

    /// <summary><c>statement.bad_range</c></summary>
    public const string StatementBadRange = "statement.bad_range";

    /// <summary><c>statement.bad_to</c></summary>
    public const string StatementBadTo = "statement.bad_to";

    /// <summary><c>statement.range_too_long</c></summary>
    public const string StatementRangeTooLong = "statement.range_too_long";

    /// <summary><c>statement.unavailable</c></summary>
    public const string StatementUnavailable = "statement.unavailable";

    /// <summary><c>transfer.bad_amount</c></summary>
    public const string TransferBadAmount = "transfer.bad_amount";

    /// <summary><c>transfer.bad_recipient</c></summary>
    public const string TransferBadRecipient = "transfer.bad_recipient";

    /// <summary><c>transfer.no_recipient</c></summary>
    public const string TransferNoRecipient = "transfer.no_recipient";

    /// <summary><c>transfer.recipient_not_found</c></summary>
    public const string TransferRecipientNotFound = "transfer.recipient_not_found";

    /// <summary><c>treasury.already_usdt</c></summary>
    public const string TreasuryAlreadyUsdt = "treasury.already_usdt";

    /// <summary><c>treasury.bad_amount</c></summary>
    public const string TreasuryBadAmount = "treasury.bad_amount";

    /// <summary><c>treasury.bad_received</c></summary>
    public const string TreasuryBadReceived = "treasury.bad_received";

    /// <summary><c>treasury.conversion_parked</c></summary>
    public const string TreasuryConversionParked = "treasury.conversion_parked";

    /// <summary><c>treasury.convert_in_flight</c></summary>
    public const string TreasuryConvertInFlight = "treasury.convert_in_flight";

    /// <summary><c>treasury.empty_fill</c></summary>
    public const string TreasuryEmptyFill = "treasury.empty_fill";

    /// <summary><c>treasury.exceeds_cold</c></summary>
    public const string TreasuryExceedsCold = "treasury.exceeds_cold";

    /// <summary><c>treasury.exceeds_free</c></summary>
    public const string TreasuryExceedsFree = "treasury.exceeds_free";

    /// <summary><c>treasury.exchange_unconfigured</c></summary>
    public const string TreasuryExchangeUnconfigured = "treasury.exchange_unconfigured";

    /// <summary><c>treasury.freeze_unknown</c></summary>
    public const string TreasuryFreezeUnknown = "treasury.freeze_unknown";

    /// <summary><c>treasury.frozen</c></summary>
    public const string TreasuryFrozen = "treasury.frozen";

    /// <summary><c>treasury.inflight_unparsable</c></summary>
    public const string TreasuryInflightUnparsable = "treasury.inflight_unparsable";

    /// <summary><c>treasury.no_address</c></summary>
    public const string TreasuryNoAddress = "treasury.no_address";

    /// <summary><c>treasury.no_ccy_map</c></summary>
    public const string TreasuryNoCcyMap = "treasury.no_ccy_map";

    /// <summary><c>treasury.no_free_balance</c></summary>
    public const string TreasuryNoFreeBalance = "treasury.no_free_balance";

    /// <summary><c>treasury.no_price</c></summary>
    public const string TreasuryNoPrice = "treasury.no_price";

    /// <summary><c>treasury.no_ref</c></summary>
    public const string TreasuryNoRef = "treasury.no_ref";

    /// <summary><c>treasury.no_target_hot</c></summary>
    public const string TreasuryNoTargetHot = "treasury.no_target_hot";

    /// <summary><c>treasury.not_configured</c></summary>
    public const string TreasuryNotConfigured = "treasury.not_configured";

    /// <summary><c>treasury.payouts_frozen</c></summary>
    public const string TreasuryPayoutsFrozen = "treasury.payouts_frozen";

    /// <summary><c>treasury.ref_destination_mismatch</c></summary>
    public const string TreasuryRefDestinationMismatch = "treasury.ref_destination_mismatch";

    /// <summary><c>treasury.ref_required</c></summary>
    public const string TreasuryRefRequired = "treasury.ref_required";

    /// <summary><c>treasury.ref_reused</c></summary>
    public const string TreasuryRefReused = "treasury.ref_reused";

    /// <summary><c>treasury.same_asset</c></summary>
    public const string TreasurySameAsset = "treasury.same_asset";

    /// <summary><c>treasury.send_in_flight</c></summary>
    public const string TreasurySendInFlight = "treasury.send_in_flight";

    /// <summary><c>treasury.unknown_asset</c></summary>
    public const string TreasuryUnknownAsset = "treasury.unknown_asset";

    /// <summary><c>treasury.vrcs_book_missing</c></summary>
    public const string TreasuryVrcsBookMissing = "treasury.vrcs_book_missing";

    /// <summary><c>tron.bad_resource</c></summary>
    public const string TronBadResource = "tron.bad_resource";

    /// <summary><c>tron.not_configured</c></summary>
    public const string TronNotConfigured = "tron.not_configured";

    /// <summary><c>tron.ref_required</c></summary>
    public const string TronRefRequired = "tron.ref_required";

    /// <summary><c>usd.parse</c></summary>
    public const string UsdParse = "usd.parse";

    /// <summary><c>vrcs.read</c></summary>
    public const string VrcsRead = "vrcs.read";

    /// <summary><c>wallet.abandoned</c></summary>
    public const string WalletAbandoned = "wallet.abandoned";

    /// <summary><c>wallet.bad_before</c></summary>
    public const string WalletBadBefore = "wallet.bad_before";

    /// <summary><c>wallet.bad_uuid</c></summary>
    public const string WalletBadUuid = "wallet.bad_uuid";

    /// <summary><c>wallet.deposits_unavailable</c></summary>
    public const string WalletDepositsUnavailable = "wallet.deposits_unavailable";

    /// <summary><c>wallet.no_address</c></summary>
    public const string WalletNoAddress = "wallet.no_address";

    /// <summary><c>wallet.no_network</c></summary>
    public const string WalletNoNetwork = "wallet.no_network";

    /// <summary><c>wallet.sandbox_unsupported</c></summary>
    public const string WalletSandboxUnsupported = "wallet.sandbox_unsupported";

    /// <summary><c>wallet.static_disabled</c></summary>
    public const string WalletStaticDisabled = "wallet.static_disabled";

    /// <summary><c>wallet.unsupported_network</c></summary>
    public const string WalletUnsupportedNetwork = "wallet.unsupported_network";

    /// <summary><c>webhook.bad_currency</c></summary>
    public const string WebhookBadCurrency = "webhook.bad_currency";

    /// <summary><c>webhook.bad_status</c></summary>
    public const string WebhookBadStatus = "webhook.bad_status";

    /// <summary><c>webhook.bad_url</c></summary>
    public const string WebhookBadUrl = "webhook.bad_url";

    /// <summary><c>webhook.bad_uuid</c></summary>
    public const string WebhookBadUuid = "webhook.bad_uuid";

    /// <summary><c>webhook.no_endpoint</c></summary>
    public const string WebhookNoEndpoint = "webhook.no_endpoint";

    /// <summary><c>webhook.no_url</c></summary>
    public const string WebhookNoUrl = "webhook.no_url";

    /// <summary><c>webhook.rotation_in_overlap</c></summary>
    public const string WebhookRotationInOverlap = "webhook.rotation_in_overlap";

    /// <summary><c>webhook.test_failed</c></summary>
    public const string WebhookTestFailed = "webhook.test_failed";

    /// <summary>Every code this snapshot knows.</summary>
    public static readonly IReadOnlyList<string> All =
    [
        "accepted.no_network", "accepted.unknown_method", "accounting.unavailable", "accuracy.out_of_range",
        "admin.bad_request", "admin.disabled", "admin.unauthorized", "analytics.bad_time",
        "apiallow.bad_cidr", "apiallow.empty", "apiallow.last_entry", "apiallow.platform_unidentifiable",
        "apiallow.too_many", "auth.bad_timestamp", "auth.body_too_large", "auth.ip_not_allowed",
        "autopilot.bad_energy", "autopilot.bad_usd", "autopilot.energy_no_free_trx", "autopilot.energy_too_large",
        "autopilot.freeze_unknown", "autopilot.frozen", "autopilot.gas_deep_deficit", "autopilot.gas_target_below_min",
        "autopilot.usd_too_large", "autowithdraw.bad_min", "autowithdraw.missing", "batch.bad_id",
        "batch.bad_recipient", "batch.disabled", "batch.duplicate_order_id", "batch.duplicate_reference",
        "batch.empty", "batch.invoice_required", "batch.not_found", "batch.order_id_required",
        "batch.reference_required", "batch.too_large", "batch.unsupported_kind", "blocklist.invalid_address",
        "blocklist.missing_fields", "blocklist.unknown_network", "cheque.token_required", "commission.bad_merchant",
        "commission.fixed_out_of_range", "commission.out_of_range", "compliance.blocked", "compliance.blocked_address",
        "compliance.blocklist_unavailable", "compliance.no_destination", "compliance.no_network", "confirmations.bad_tier",
        "confirmations.no_network", "confirmations.tier_too_large", "db.unavailable", "deposit.generation_stale",
        "discount.out_of_range", "document.bad_format", "document.bad_id", "document.bad_job_id",
        "document.bad_kind", "document.bad_signature", "document.balance_unavailable", "document.batch_unavailable",
        "document.daily_quota", "document.disabled", "document.encode_failed", "document.fees_unavailable",
        "document.job_expired", "document.job_failed", "document.job_not_found", "document.job_not_ready",
        "document.jobs_disabled", "document.ledger_unavailable", "document.link_expired", "document.no_split",
        "document.not_found", "document.render_failed", "document.render_rejected", "document.render_unavailable",
        "document.too_many_jobs", "document.unknown_kind", "document.unknown_lang", "document.wallet_abandoned",
        "document.wallet_blocked", "email.bad_recipient", "email.disabled", "email.no_recipient",
        "email.rate_limited", "history.bad_merchant_id", "idempotency.bad_key", "idempotency.in_progress",
        "idempotency.key_reused", "idempotency.unavailable", "internal", "invoice.address_failed",
        "invoice.already_paid", "invoice.bad_deposit", "invoice.bad_id", "invoice.bad_price",
        "invoice.bad_reversal_amount", "invoice.deposit_asset_mismatch", "invoice.deposit_exists", "invoice.deposit_pending",
        "invoice.expired", "invoice.fiat_pay_asset", "invoice.generation_stale", "invoice.no_pay_asset",
        "invoice.no_user", "invoice.not_payable", "invoice.not_selectable", "invoice.nothing_due",
        "invoice.partially_paid", "invoice.pay_asset_not_selected", "invoice.quote_failed", "invoice.refresh_lease",
        "invoice.refresh_not_expired", "invoice.refresh_paid", "invoice.refresh_select", "killswitch.reason_required",
        "killswitch.unavailable", "ledger.asset_mismatch", "ledger.idempotency_conflict", "ledger.sandbox_live_mix",
        "ledger.unavailable", "merchant.already_sandbox", "merchant.bad_fee_bearer", "merchant.bad_id",
        "merchant.bad_project_id", "merchant.bad_settles_to", "merchant.bad_signature", "merchant.bad_subtract",
        "merchant.close_unavailable", "merchant.email_required", "merchant.key_mode_mismatch", "merchant.no_owner",
        "merchant.no_personal_wallet", "merchant.not_found", "merchant.project_mismatch", "merchant.secret_decrypt",
        "merchant.unknown_key", "minimum.negative", "minimum.no_network", "onramp.admit",
        "onramp.advance", "onramp.already_delivered", "onramp.bad_invoice", "onramp.bad_status",
        "onramp.captured", "onramp.expire", "onramp.fail_captured", "onramp.for_invoice",
        "onramp.force_completed", "onramp.invoice_not_found", "onramp.invoice_not_payable", "onramp.money_already_landed",
        "onramp.no_evidence", "onramp.no_refund_evidence", "onramp.not_captured", "onramp.not_found",
        "onramp.open", "onramp.open_conflict", "onramp.overdue", "onramp.owner_required",
        "onramp.refund_evidence", "onramp.release", "onramp.suppressed_in", "onramp.suppresses",
        "onramp.target_required", "onramp.terminal", "onramp.token", "pay.bad_uuid",
        "pay.below_minimum", "pay.discount_unavailable", "pay.method_not_accepted", "pay.minimum_unavailable",
        "pay.not_selectable", "paylink.above_max", "paylink.amount_required", "paylink.bad_amount",
        "paylink.bad_bounds", "paylink.bad_id", "paylink.bad_max", "paylink.bad_min",
        "paylink.bad_mode", "paylink.bad_range", "paylink.below_min", "paylink.disabled",
        "paylink.expires_in_negative", "paylink.expires_in_too_large", "paylink.not_found", "paylink.not_positive",
        "paylink.order_id_invalid", "paylink.order_id_too_long", "paylink.rate_limited", "paylink.unavailable",
        "payment.bad_accuracy", "payment.bad_amount", "payment.bad_payer_email", "payment.bad_redirect_url",
        "payment.bad_status", "payment.bad_subtract", "payment.bad_url_callback", "payment.bad_uuid",
        "payment.below_minimum", "payment.discount_unavailable", "payment.minimum_unavailable", "payment.network_required",
        "payment.no_lookup", "payment.not_found", "payment.subtract_impossible", "payment.to_currency_required",
        "payment.unknown_to_currency", "payment.unsupported_network", "payout.address_network_mismatch", "payout.amount_below_fee",
        "payout.approver_is_creator", "payout.asset_mismatch", "payout.bad_address", "payout.bad_amount",
        "payout.bad_kind", "payout.bad_memo", "payout.bad_owner_kind", "payout.bad_state",
        "payout.bad_status", "payout.bad_url_callback", "payout.bad_user", "payout.bad_uuid",
        "payout.batch_too_large", "payout.broadcast_in_flight", "payout.convert_bad_amount", "payout.convert_frozen",
        "payout.convert_insufficient", "payout.convert_no_rate", "payout.convert_same_asset", "payout.convert_unsupported",
        "payout.destination_internal", "payout.empty_batch", "payout.fee_asset_mismatch", "payout.freeze_unknown",
        "payout.from_currency_unsupported", "payout.frozen", "payout.funds_maturing", "payout.insufficient_funds",
        "payout.memo_conflict", "payout.memo_required", "payout.memo_too_long", "payout.no_destination",
        "payout.no_lookup", "payout.no_owner", "payout.no_sender", "payout.no_txid",
        "payout.no_user", "payout.not_broadcasting", "payout.not_found", "payout.not_pending",
        "payout.not_sent", "payout.order_id_required", "payout.reference_collision", "payout.release_reason_required",
        "payout.reserved_reference", "payout.test_merchant", "payout_link.disabled", "payoutctl.bad_body",
        "payoutctl.bad_cap", "payoutctl.bad_source", "payoutctl.unavailable", "payoutlink.already_claimed",
        "payoutlink.bad_amount", "payoutlink.bad_fee_bearer", "payoutlink.bad_id", "payoutlink.bad_passcode",
        "payoutlink.bad_state", "payoutlink.batch_too_large", "payoutlink.cancelled", "payoutlink.claim_in_progress",
        "payoutlink.destination_internal", "payoutlink.disabled", "payoutlink.duplicate_reference", "payoutlink.empty_batch",
        "payoutlink.expired", "payoutlink.funds_maturing", "payoutlink.idempotency_required", "payoutlink.insufficient_funds",
        "payoutlink.no_address", "payoutlink.not_found", "payoutlink.not_funded", "payoutlink.passcode",
        "payoutlink.passcode_locked", "payoutlink.passcode_required", "payoutlink.passcode_wrong", "payoutlink.reference_required",
        "payoutlink.token", "payoutlink.unavailable", "payoutlink.unsupported_network", "personal.amount_invalid",
        "personal.amount_too_small", "personal.asset_mismatch", "personal.bad_amount", "personal.bad_deposit_id",
        "personal.bad_fund_id", "personal.bad_hold_amount", "personal.bad_hold_id", "personal.bad_source",
        "personal.bad_source_id", "personal.bad_stake_amount", "personal.conversions_frozen", "personal.convert_unsupported",
        "personal.funds_maturing", "personal.hold_claimed", "personal.hold_idem_reuse", "personal.hold_kind",
        "personal.hold_no_recipient", "personal.hold_not_found", "personal.hold_settled", "personal.idempotency_conflict",
        "personal.insufficient", "personal.interest_excessive", "personal.no_idem", "personal.no_recipient",
        "personal.no_user", "personal.recipient_not_found", "personal.self_transfer", "personal.stake_not_found",
        "postgres.lock_pool_busy", "qr.no_address", "quarantine.bad_amount", "quarantine.credit_reversed",
        "quarantine.not_open", "quarantine.test_merchant", "quarantine.unknown_asset", "quarantine.unknown_merchant",
        "rate.unavailable", "rates.deviation", "rates.fiat_pay_asset", "rates.no_pay_asset",
        "rates.no_source", "rates.non_positive", "rates.stale_rate", "rates.unavailable",
        "referral.disabled", "referral.no_code", "referral.no_tiers", "referral.out_of_range",
        "refund.bad_amount", "refund.chain_ambiguous", "refund.destination_internal", "refund.dust",
        "refund.exceeds_excess", "refund.exceeds_refundable", "refund.fence_check", "refund.no_address",
        "refund.nothing_to_refund", "refund.paid_internally", "refund.reference_collision", "refund.too_many_attempts",
        "report.too_large", "request.bad_id", "request.bad_json", "request.body_read",
        "request.conflicting_field", "request.control_char", "request.duplicate_field", "request.method_not_allowed",
        "request.missing_field", "request.not_found", "request.nul_byte", "request.rate_limited",
        "request.reference_invalid", "request.reference_too_long", "request.too_deep", "request.unknown_currency",
        "request.unreadable", "resolution.already_refunded", "resolution.already_resolved", "resolution.bad_action",
        "resolution.chain_ambiguous", "resolution.disabled", "resolution.not_underpaid", "routing.awaiting_settle",
        "routing.onramp_check_failed", "routing.refund_in_flight", "routing.refund_payer_unresolved", "routing.share_payout_check_failed",
        "routing.share_reattempts_exhausted", "routing.underpay_unresolved", "sandbox.amount_too_large", "sandbox.bad_amount",
        "sandbox.bad_asset", "sandbox.bad_delivery", "sandbox.bad_invoice", "sandbox.convert_not_available",
        "sandbox.delivery_not_found", "sandbox.invoice_not_found", "sandbox.live_key", "sandbox.transfer_not_available",
        "split.bad_destination", "split.bad_hold", "split.bad_id", "split.bad_merchant",
        "split.bad_percent", "split.bad_reversal_claim", "split.consent_check_failed", "split.dest_check_failed",
        "split.dest_not_found", "split.disabled", "split.duplicate_destination", "split.network_required",
        "split.not_found", "split.recipient_not_opted_in", "split.self_destination", "statement.bad_from",
        "statement.bad_range", "statement.bad_to", "statement.range_too_long", "statement.unavailable",
        "transfer.bad_amount", "transfer.bad_recipient", "transfer.no_recipient", "transfer.recipient_not_found",
        "treasury.already_usdt", "treasury.bad_amount", "treasury.bad_received", "treasury.conversion_parked",
        "treasury.convert_in_flight", "treasury.empty_fill", "treasury.exceeds_cold", "treasury.exceeds_free",
        "treasury.exchange_unconfigured", "treasury.freeze_unknown", "treasury.frozen", "treasury.inflight_unparsable",
        "treasury.no_address", "treasury.no_ccy_map", "treasury.no_free_balance", "treasury.no_price",
        "treasury.no_ref", "treasury.no_target_hot", "treasury.not_configured", "treasury.payouts_frozen",
        "treasury.ref_destination_mismatch", "treasury.ref_required", "treasury.ref_reused", "treasury.same_asset",
        "treasury.send_in_flight", "treasury.unknown_asset", "treasury.vrcs_book_missing", "tron.bad_resource",
        "tron.not_configured", "tron.ref_required", "usd.parse", "vrcs.read",
        "wallet.abandoned", "wallet.bad_before", "wallet.bad_uuid", "wallet.deposits_unavailable",
        "wallet.no_address", "wallet.no_network", "wallet.sandbox_unsupported", "wallet.static_disabled",
        "wallet.unsupported_network", "webhook.bad_currency", "webhook.bad_status", "webhook.bad_url",
        "webhook.bad_uuid", "webhook.no_endpoint", "webhook.no_url", "webhook.rotation_in_overlap",
        "webhook.test_failed",
    ];
}
