// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core 7ec04293c426).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

using System.Text.Json.Serialization;

namespace Oblodai.Contract;

/// <summary>Request body of <c>POST /v1/api-allowlist/add</c>.</summary>
public sealed record ApiAllowlistAddRequest
{
    /// <summary>IP or subnet in CIDR notation (203.0.113.7 or 203.0.113.0/24). Example: <c>"203.0.113.0/24"</c>.</summary>
    [JsonPropertyName("cidr")]
    public required string Cidr { get; init; }
}

/// <summary>Request body of <c>POST /v1/api-allowlist/enable</c>.</summary>
public sealed record ApiAllowlistEnableRequest
{
    /// <summary>true — accept API calls only from listed addresses; false — the list is kept but not enforced. Example: <c>true</c>.</summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }
}

/// <summary>Request body of <c>POST /v1/api-allowlist/remove</c>.</summary>
public sealed record ApiAllowlistRemoveRequest
{
    /// <summary>IP or subnet in CIDR notation (203.0.113.7 or 203.0.113.0/24). Example: <c>"203.0.113.0/24"</c>.</summary>
    [JsonPropertyName("cidr")]
    public required string Cidr { get; init; }
}

/// <summary>Request body of <c>POST /v1/auto-withdraw/delete</c>.</summary>
public sealed record AutoWithdrawDeleteRequest
{
    /// <summary>Asset whose auto-withdrawal to switch off. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }
}

/// <summary>Request body of <c>POST /v1/auto-withdraw/set</c>.</summary>
public sealed record AutoWithdrawSetRequest
{
    /// <summary>Destination address (the merchant's external wallet). Example: <c>"TQrY8bkbpXKPt2LZbU8jqfnpFbUSF15sbx"</c>.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Asset to withdraw automatically. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Threshold: the sweep runs once the available balance of the asset reaches this amount; empty uses the network minimum. Decimal string, never a float. Example: <c>"100"</c>.</summary>
    [JsonPropertyName("min_amount")]
    public string? MinAmount { get; init; }

    /// <summary>Network of the destination address. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public required Network Network { get; init; }
}

/// <summary>Request body of <c>POST /v1/batch/info</c>.</summary>
public sealed record BatchInfoRequest
{
    /// <summary>Batch id from the submit response. Example: <c>"9f4c1a2b-77de-4a55-9c1f-0e2b3d4a5f60"</c>.</summary>
    [JsonPropertyName("batch_id")]
    public required string BatchId { get; init; }

    /// <summary>How many items to return in items (pagination). Example: <c>100</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset over items. Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/claim/{token}</c>.</summary>
public sealed record ClaimRequest
{
    /// <summary>Recipient address in the payout network.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Memo/tag — only for networks where it is required.</summary>
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }

    /// <summary>Claim code — if the sender set one on the link. After 10 incorrect attempts the link is locked.</summary>
    [JsonPropertyName("passcode")]
    public string? Passcode { get; init; }
}

/// <summary>Request body of <c>POST /v1/documents/jobs</c>.</summary>
public sealed record DocumentsJobsRequest
{
    /// <summary>File format: pdf (default) or csv. CSV is generated without layout — cheaper for large statements and loads into Excel/1C. Example: <c>"csv"</c>.</summary>
    [JsonPropertyName("format")]
    public string? Format { get; init; }

    /// <summary>Start of the period, YYYY-MM-DD (defaults to the first day of the current month). Example: <c>"2025-01-01"</c>.</summary>
    [JsonPropertyName("from")]
    public string? From { get; init; }

    /// <summary>Report type: statement (operations), fees (commissions) or ledger (balance movements). Example: <c>"statement"</c>.</summary>
    [JsonPropertyName("kind")]
    public required string Kind { get; init; }

    /// <summary>Document language (default en). Example: <c>"ru"</c>.</summary>
    [JsonPropertyName("lang")]
    public string? Lang { get; init; }

    /// <summary>End of the period, inclusive, YYYY-MM-DD (defaults to today). The period may span up to two years. Example: <c>"2026-08-19"</c>.</summary>
    [JsonPropertyName("to")]
    public string? To { get; init; }
}

/// <summary>Request body of <c>POST /v1/documents/jobs/info</c>.</summary>
public sealed record DocumentsJobsInfoRequest
{
    /// <summary>Job id from the creation response.</summary>
    [JsonPropertyName("job_id")]
    public required string JobId { get; init; }
}

/// <summary>Request body of <c>POST /v1/exchange-rate/list</c>.</summary>
public sealed record ExchangeRateListRequest
{
    /// <summary>Currency code. If set, only its rate is returned. If empty or the body is {}, rates for all currencies are returned. Example: <c>"ETH"</c>.</summary>
    [JsonPropertyName("currency_from")]
    public string? CurrencyFrom { get; init; }

    /// <summary>Quote currency: USDT by default; any pricing asset, including fiats with a direct feed (EUR, RUB, …).</summary>
    [JsonPropertyName("currency_to")]
    public string? CurrencyTo { get; init; }

    /// <summary>Page size, 1–100; default 25.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list; default 0.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/link/{id}/checkout</c>.</summary>
public sealed record LinkCheckoutRequest
{
    /// <summary>Amount entered by the buyer, in the link's price currency; required for open and range, ignored for fixed. Decimal string, never a float. Example: <c>"10.00"</c>.</summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; init; }

    /// <summary>Settlement currency — the coin the buyer pays with; needed only if the link did not pin pinned_currency. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Settlement network; needed only if the link did not pin pinned_network. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Shop order number from the embedded widget (data-oblodai-order-id); carried over to the invoice and to the webhook for matching with the order; not an idempotency key.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Buyer email — the cheque is sent there automatically after payment. Example: <c>"buyer@example.com"</c>.</summary>
    [JsonPropertyName("payer_email")]
    public string? PayerEmail { get; init; }
}

/// <summary>Request body of <c>POST /v1/merchants</c>.</summary>
public sealed record MerchantsRequest
{
    /// <summary>Owner email; must be unique across merchants. Example: <c>"owner@shop.example"</c>.</summary>
    [JsonPropertyName("email")]
    public required string Email { get; init; }

    /// <summary>Display name of the merchant. Example: <c>"Acme"</c>.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }
}

/// <summary>Request body of <c>POST /v1/pay/{id}/select</c>.</summary>
public sealed record PaySelectRequest
{
    /// <summary>Selected payment currency. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Selected network. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public required Network Network { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment</c>.</summary>
public sealed record PaymentRequest
{
    /// <summary>Under/overpayment tolerance, 0–5 %. Overrides the merchant setting.</summary>
    [JsonPropertyName("accuracy_payment_percent")]
    public decimal? AccuracyPaymentPercent { get; init; }

    /// <summary>Private merchant data, echoed back in webhooks (not visible to the buyer).</summary>
    [JsonPropertyName("additional_data")]
    public string? AdditionalData { get; init; }

    /// <summary>Amount to pay, in currency. Decimal string, never a float. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Price currency code: any of the 23 fiats (USD, EUR, RUB, …) or any coin (USDT, BTC, …). JPY and KRW have zero decimal places. Example: <c>"USD"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Allow paying up the remaining amount.</summary>
    [JsonPropertyName("is_payment_multiple")]
    public bool? IsPaymentMultiple { get; init; }

    /// <summary>Revive an expired invoice by order_id instead of creating a new one.</summary>
    [JsonPropertyName("is_refresh")]
    public bool? IsRefresh { get; init; }

    /// <summary>Invoice lifetime in seconds, 300–43200; default 3600. Values outside the range are clamped to the nearest bound. Example: <c>3600</c>.</summary>
    [JsonPropertyName("lifetime_seconds")]
    public int? LifetimeSeconds { get; init; }

    /// <summary>Settlement network (e.g. tron, ethereum). Optional — see the currency and network selection modes. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Merchant reference; idempotency key. Strongly recommended. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Payer email. If set, a cheque is sent there automatically after payment; it is also the default recipient for POST /v1/payment/send-email.</summary>
    [JsonPropertyName("payer_email")]
    public string? PayerEmail { get; init; }

    /// <summary>Deprecated: % of the network markup charged to the payer (0–100); payer-facing markups are configured via discount.</summary>
    [JsonPropertyName("subtract")]
    public int? Subtract { get; init; }

    /// <summary>Payment page theme: dark | light. Example: <c>"dark"</c>.</summary>
    [JsonPropertyName("theme")]
    public string? Theme { get; init; }

    /// <summary>Settlement currency — the crypto used for payment. Defaults to currency (only if currency is a coin); with a fiat price set it explicitly or omit it together with network. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("to_currency")]
    public string? ToCurrency { get; init; }

    /// <summary>Per-invoice webhook. Requires a registered endpoint (POST /v1/webhooks): delivery is signed with its secret.</summary>
    [JsonPropertyName("url_callback")]
    public string? UrlCallback { get; init; }

    /// <summary>"Back to shop" link on the payment page.</summary>
    [JsonPropertyName("url_return")]
    public string? UrlReturn { get; init; }

    /// <summary>Redirect after successful payment.</summary>
    [JsonPropertyName("url_success")]
    public string? UrlSuccess { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/accepted/list</c>.</summary>
public sealed record PaymentAcceptedListRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/accepted/set</c>.</summary>
public sealed record PaymentAcceptedSetRequest
{
    /// <summary>The full list of currency+network pairs payers may use; an empty list accepts everything in the catalog.</summary>
    [JsonPropertyName("accepted")]
    public required IReadOnlyList<PaymentAcceptedSetAcceptedItem> Accepted { get; init; }
}

/// <summary>One item of <c>accepted</c> in <c>POST /v1/payment/accepted/set</c>.</summary>
public sealed record PaymentAcceptedSetAcceptedItem
{
    /// <summary>Asset code. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Asset network. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public required Network Network { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/accuracy/set</c>.</summary>
public sealed record PaymentAccuracySetRequest
{
    /// <summary>Tolerance in percent, 1–5. Required when enabled: true; ignored when enabled: false (reset to 0). Capped at 5 %. Example: <c>2</c>.</summary>
    [JsonPropertyName("accuracy_percent")]
    public int? AccuracyPercent { get; init; }

    /// <summary>Enable/disable the tolerance. Example: <c>true</c>.</summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/autorefund/set</c>.</summary>
public sealed record PaymentAutorefundSetRequest
{
    /// <summary>Refund the excess on overpayment (paid_over). Example: <c>true</c>.</summary>
    [JsonPropertyName("overpay")]
    public required bool Overpay { get; init; }

    /// <summary>Refund the funds on an expired underpayment (wrong_amount). Example: <c>true</c>.</summary>
    [JsonPropertyName("underpay")]
    public required bool Underpay { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/batch</c>.</summary>
public sealed record PaymentBatchRequest
{
    /// <summary>What to do when an item fails: continue (default) — process the rest; stop — halt processing after the first error. Example: <c>"continue"</c>.</summary>
    [JsonPropertyName("on_error")]
    public BatchOnError? OnError { get; init; }

    /// <summary>Array of 1 to 5000 items — the same fields as POST /v1/payment; set order_id on every item: results are matched by it and it protects against duplicates.</summary>
    [JsonPropertyName("payments")]
    public required IReadOnlyList<PaymentBatchPaymentsItem> Payments { get; init; }
}

/// <summary>One item of <c>payments</c> in <c>POST /v1/payment/batch</c>.</summary>
public sealed record PaymentBatchPaymentsItem
{
    /// <summary>Under/overpayment tolerance, 0–5 %. Overrides the merchant setting.</summary>
    [JsonPropertyName("accuracy_payment_percent")]
    public decimal? AccuracyPaymentPercent { get; init; }

    /// <summary>Private merchant data, echoed back in webhooks (not visible to the buyer).</summary>
    [JsonPropertyName("additional_data")]
    public string? AdditionalData { get; init; }

    /// <summary>Amount to pay, in currency. Decimal string, never a float. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Price currency code: any of the 23 fiats (USD, EUR, RUB, …) or any coin (USDT, BTC, …). JPY and KRW have zero decimal places. Example: <c>"USD"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Allow paying up the remaining amount.</summary>
    [JsonPropertyName("is_payment_multiple")]
    public bool? IsPaymentMultiple { get; init; }

    /// <summary>Revive an expired invoice by order_id instead of creating a new one.</summary>
    [JsonPropertyName("is_refresh")]
    public bool? IsRefresh { get; init; }

    /// <summary>Invoice lifetime in seconds, 300–43200; default 3600. Values outside the range are clamped to the nearest bound. Example: <c>3600</c>.</summary>
    [JsonPropertyName("lifetime_seconds")]
    public int? LifetimeSeconds { get; init; }

    /// <summary>Settlement network (e.g. tron, ethereum). Optional — see the currency and network selection modes. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Merchant reference; idempotency key. Strongly recommended. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>Payer email. If set, a cheque is sent there automatically after payment; it is also the default recipient for POST /v1/payment/send-email.</summary>
    [JsonPropertyName("payer_email")]
    public string? PayerEmail { get; init; }

    /// <summary>Deprecated: % of the network markup charged to the payer (0–100); payer-facing markups are configured via discount.</summary>
    [JsonPropertyName("subtract")]
    public int? Subtract { get; init; }

    /// <summary>Payment page theme: dark | light. Example: <c>"dark"</c>.</summary>
    [JsonPropertyName("theme")]
    public string? Theme { get; init; }

    /// <summary>Settlement currency — the crypto used for payment. Defaults to currency (only if currency is a coin); with a fiat price set it explicitly or omit it together with network. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("to_currency")]
    public string? ToCurrency { get; init; }

    /// <summary>Per-invoice webhook. Requires a registered endpoint (POST /v1/webhooks): delivery is signed with its secret.</summary>
    [JsonPropertyName("url_callback")]
    public string? UrlCallback { get; init; }

    /// <summary>"Back to shop" link on the payment page.</summary>
    [JsonPropertyName("url_return")]
    public string? UrlReturn { get; init; }

    /// <summary>Redirect after successful payment.</summary>
    [JsonPropertyName("url_success")]
    public string? UrlSuccess { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/cancel</c>.</summary>
public sealed record PaymentCancelRequest
{
    /// <summary>Your order reference. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/discount/list</c>.</summary>
public sealed record PaymentDiscountListRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/discount/set</c>.</summary>
public sealed record PaymentDiscountSetRequest
{
    /// <summary>Currency. Empty = global default for all coins. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Percentage, from -99 to 99. Positive is a discount, negative is a markup. Example: <c>3</c>.</summary>
    [JsonPropertyName("discount_percent")]
    public required int DiscountPercent { get; init; }

    /// <summary>Network. Empty = any network of this currency. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/fee-config/set</c>.</summary>
public sealed record PaymentFeeConfigSetRequest
{
    /// <summary>Share of OUR commission paid by the buyer: 0 — the merchant pays (current behaviour), 100 — the buyer pays and the invoice is issued with a markup. Applies to invoices created AFTER the change. Example: <c>100</c>.</summary>
    [JsonPropertyName("payer_pays_percent")]
    public required int PayerPaysPercent { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/history</c>.</summary>
public sealed record PaymentHistoryRequest
{
    /// <summary>Ignored on this route (payout history only). Example: <c>"payout"</c>.</summary>
    [JsonPropertyName("kind")]
    public string? Kind { get; init; }

    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }

    /// <summary>Filter by status (an exact value from the status vocabulary); empty returns all. Example: <c>"paid"</c>.</summary>
    [JsonPropertyName("status")]
    public PaymentStatus? Status { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/info</c>.</summary>
public sealed record PaymentInfoRequest
{
    /// <summary>Your order reference. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/link</c>.</summary>
public sealed record PaymentLinkRequest
{
    /// <summary>Amount — for fixed mode; required in this mode. Decimal string, never a float. Example: <c>"25.00"</c>.</summary>
    [JsonPropertyName("amount_fixed")]
    public string? AmountFixed { get; init; }

    /// <summary>Amount mode: fixed | open | range. Example: <c>"open"</c>.</summary>
    [JsonPropertyName("amount_mode")]
    public required AmountMode AmountMode { get; init; }

    /// <summary>Price currency — fiat (USD, EUR, RUB, …) or a coin; see pricing_currencies from GET /v1/currencies. Example: <c>"USD"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Description on the payment page.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>Link lifetime in seconds from creation; 0 (default) — the link never expires.</summary>
    [JsonPropertyName("expires_in_seconds")]
    public int? ExpiresInSeconds { get; init; }

    /// <summary>Upper bound — for range; required in this mode. Decimal string, never a float. Example: <c>"1000.00"</c>.</summary>
    [JsonPropertyName("max_amount")]
    public string? MaxAmount { get; init; }

    /// <summary>Lower bound: an optional floor for open, a required minimum for range. Decimal string, never a float. Example: <c>"1.00"</c>.</summary>
    [JsonPropertyName("min_amount")]
    public string? MinAmount { get; init; }

    /// <summary>Settlement currency (coin) pinned to the link; empty — the buyer chooses the coin. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("pinned_currency")]
    public string? PinnedCurrency { get; init; }

    /// <summary>Settlement network pinned to the link; empty — the buyer chooses the network. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("pinned_network")]
    public Network? PinnedNetwork { get; init; }

    /// <summary>Title on the payment page.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/link/info</c>.</summary>
public sealed record PaymentLinkInfoRequest
{
    /// <summary>Page size for the link's payments, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Payment link identifier. Example: <c>"5d3f2a71-9c84-4b0e-8d17-3e6a2c9f1b40"</c>.</summary>
    [JsonPropertyName("link_id")]
    public required string LinkId { get; init; }

    /// <summary>Offset within the link's payments. Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/link/list</c>.</summary>
public sealed record PaymentLinkListRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/link/toggle</c>.</summary>
public sealed record PaymentLinkToggleRequest
{
    /// <summary>true — the link accepts payments; false — disabled (the page shows the link as inactive). Example: <c>false</c>.</summary>
    [JsonPropertyName("active")]
    public required bool Active { get; init; }

    /// <summary>Payment link identifier. Example: <c>"5d3f2a71-9c84-4b0e-8d17-3e6a2c9f1b40"</c>.</summary>
    [JsonPropertyName("link_id")]
    public required string LinkId { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/qr</c>.</summary>
public sealed record PaymentQrRequest
{
    /// <summary>Your order reference. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/refund</c>.</summary>
public sealed record PaymentRefundRequest
{
    /// <summary>Refund destination address. Defaults to the payment's payer_address; required only for Bitcoin/UTXO.</summary>
    [JsonPropertyName("address")]
    public string? Address { get; init; }

    /// <summary>Partial amount. Defaults to the full amount received. Decimal string, never a float. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; init; }

    /// <summary>Network. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your order reference for the payment. Either uuid or order_id is required. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Optional refund idempotency key: distinguishes two different refunds with the same (payment, address, amount); a repeat with the same value is deduplicated. This is not order_id.</summary>
    [JsonPropertyName("reference")]
    public string? Reference { get; init; }

    /// <summary>Payment id. Either uuid or order_id is required.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/resend</c>.</summary>
public sealed record PaymentResendRequest
{
    /// <summary>Your order reference. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/resolve</c>.</summary>
public sealed record PaymentResolveRequest
{
    /// <summary>accept — accept the partial payment, refund — return it to the payer. One of <c>accept</c>, <c>refund</c>. Example: <c>"accept"</c>.</summary>
    [JsonPropertyName("action")]
    public required string Action { get; init; }

    /// <summary>refund only: refund address. Defaults to the payment's recorded payer_address; if it is empty (Bitcoin/UTXO) the address is required, otherwise refund.no_address.</summary>
    [JsonPropertyName("address")]
    public string? Address { get; init; }

    /// <summary>refund only: refund network, defaults to the payment network.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your payment identifier. Example: <c>"ord-1001"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>refund only: your refund deduplication key.</summary>
    [JsonPropertyName("reference")]
    public string? Reference { get; init; }

    /// <summary>Payment UUID. Either uuid or order_id is required.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/send-email</c>.</summary>
public sealed record PaymentSendEmailRequest
{
    /// <summary>Where to send it. Defaults to the payer_email set on the payment. Example: <c>"buyer@example.com"</c>.</summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>Your order reference. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Payment id in Oblodai. Either uuid or order_id is required.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/services</c>.</summary>
public sealed record PaymentServicesRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payment/testing-webhook</c>.</summary>
public sealed record PaymentTestingWebhookRequest
{
    /// <summary>Status in the body. Default paid. Example: <c>"paid"</c>.</summary>
    [JsonPropertyName("status")]
    public PaymentStatus? Status { get; init; }

    /// <summary>Where to send the test body. If not provided, delivery goes to the project's registered endpoint; without an endpoint it fails with webhook.no_endpoint. Signed with the project endpoint's secret, including when url is passed explicitly. Example: <c>"https://shop.example/hook"</c>.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout</c>.</summary>
public sealed record PayoutRequest
{
    /// <summary>Recipient address.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Payout amount, in currency. Decimal string, never a float. Example: <c>"25"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (for example USDT). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Fund the payout by converting the balance. USDT → currency only. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("from_currency")]
    public string? FromCurrency { get; init; }

    /// <summary>Who pays the network fee: true — amount+fee is debited from the balance and the recipient receives amount; false — the recipient receives amount-fee; not provided — the project fee-config.</summary>
    [JsonPropertyName("is_subtract")]
    public bool? IsSubtract { get; init; }

    /// <summary>Destination tag/memo (TON Jetton). Maximum 120 characters.</summary>
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }

    /// <summary>Network (tron, ethereum, …). Required for coins with several networks. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your payout number; idempotency key. Example: <c>"payout-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>Origin label: api (default) or manual.</summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST /v1/webhooks): delivery is signed with its secret.</summary>
    [JsonPropertyName("url_callback")]
    public string? UrlCallback { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/approve</c>.</summary>
public sealed record PayoutApproveRequest
{
    /// <summary>Payout id.</summary>
    [JsonPropertyName("uuid")]
    public required string Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/batch</c>.</summary>
public sealed record PayoutBatchRequest
{
    /// <summary>What to do when an item fails: continue (default) — process the rest; stop — halt processing after the first error. Example: <c>"continue"</c>.</summary>
    [JsonPropertyName("on_error")]
    public BatchOnError? OnError { get; init; }

    /// <summary>Array of 1 to 5000 items — the same fields as POST /v1/payout; order_id is required on every item and serves as the idempotency key: a repeat returns the already created payout.</summary>
    [JsonPropertyName("payouts")]
    public required IReadOnlyList<PayoutBatchPayoutsItem> Payouts { get; init; }
}

/// <summary>One item of <c>payouts</c> in <c>POST /v1/payout/batch</c>.</summary>
public sealed record PayoutBatchPayoutsItem
{
    /// <summary>Recipient address.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Payout amount, in currency. Decimal string, never a float. Example: <c>"25"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (for example USDT). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Fund the payout by converting the balance. USDT → currency only. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("from_currency")]
    public string? FromCurrency { get; init; }

    /// <summary>Who pays the network fee: true — amount+fee is debited from the balance and the recipient receives amount; false — the recipient receives amount-fee; not provided — the project fee-config.</summary>
    [JsonPropertyName("is_subtract")]
    public bool? IsSubtract { get; init; }

    /// <summary>Destination tag/memo (TON Jetton). Maximum 120 characters.</summary>
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }

    /// <summary>Network (tron, ethereum, …). Required for coins with several networks. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your payout number; idempotency key. Example: <c>"payout-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>Origin label: api (default) or manual.</summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST /v1/webhooks): delivery is signed with its secret.</summary>
    [JsonPropertyName("url_callback")]
    public string? UrlCallback { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/calculate</c>.</summary>
public sealed record PayoutCalculateRequest
{
    /// <summary>Payout amount as a decimal string. Decimal string, never a float. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Payout asset (USDT, BTC, …). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>true — the fee is debited from the balance on top of the amount (the recipient gets exactly amount); false — the fee is taken out of the payout.</summary>
    [JsonPropertyName("is_subtract")]
    public bool? IsSubtract { get; init; }

    /// <summary>Payout network; required when the asset lives on several networks. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/cancel</c>.</summary>
public sealed record PayoutCancelRequest
{
    /// <summary>Id of the payout (or refund) to cancel.</summary>
    [JsonPropertyName("uuid")]
    public required string Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/fee-config/set</c>.</summary>
public sealed record PayoutFeeConfigSetRequest
{
    /// <summary>true — the recipient pays the network fee (receives less); false — the merchant bears the fee. Example: <c>true</c>.</summary>
    [JsonPropertyName("fee_on_recipient")]
    public required bool FeeOnRecipient { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/history</c>.</summary>
public sealed record PayoutHistoryRequest
{
    /// <summary>payout — ordinary payouts, refund — refunds; empty returns both. One of <c>payout</c>, <c>refund</c>. Example: <c>"payout"</c>.</summary>
    [JsonPropertyName("kind")]
    public string? Kind { get; init; }

    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }

    /// <summary>Filter by status (an exact value from the status vocabulary); empty returns all. Example: <c>"paid"</c>.</summary>
    [JsonPropertyName("status")]
    public PayoutStatus? Status { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/info</c>.</summary>
public sealed record PayoutInfoRequest
{
    /// <summary>Your order reference. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/link</c>.</summary>
public sealed record PayoutLinkRequest
{
    /// <summary>Amount in currency, as a string; greater than zero. Decimal string, never a float. Example: <c>"25"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Payout crypto asset (USDT, BTC, …); fiat is not possible. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>If set, the recipient receives an email with a "Claim funds" button; a delivery failure does not cancel link creation. Example: <c>"user@example.com"</c>.</summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>Link lifetime in seconds, clamped to 3600–2592000 (one hour to 30 days); without the field or with 0 the link lives 1 hour, not the maximum — set it explicitly. Example: <c>604800</c>.</summary>
    [JsonPropertyName("expires_in_seconds")]
    public int? ExpiresInSeconds { get; init; }

    /// <summary>Who pays the network fee: "recipient" (default — deducted from the amount, the recipient receives less) or "merchant" (the amount plus the fee is reserved, the recipient receives exactly amount). Example: <c>"merchant"</c>.</summary>
    [JsonPropertyName("fee_bearer")]
    public FeeBearer? FeeBearer { get; init; }

    /// <summary>Payout network for the recipient (tron, bitcoin, …). Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public required Network Network { get; init; }

    /// <summary>Message to the recipient (shown on the claim page and in the email).</summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }

    /// <summary>Claim code — a second factor for the link: "auto" — we generate it and return it ONCE in the response, or your own (6–64 visible characters), empty — no code. Pass the code to the recipient over a channel SEPARATE from the link (it is not put into the email); after 10 incorrect attempts the link is locked. Example: <c>"auto"</c>.</summary>
    [JsonPropertyName("passcode")]
    public string? Passcode { get; init; }

    /// <summary>Your deduplication key, unique per merchant; the Idempotency-Key header has no effect on this endpoint. Example: <c>"bonus-42"</c>.</summary>
    [JsonPropertyName("reference")]
    public string? Reference { get; init; }

    /// <summary>Title — shown to the recipient on the claim page.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/link/batch</c>.</summary>
public sealed record PayoutLinkBatchRequest
{
    /// <summary>Up to 500 links per call; each one succeeds or fails independently, the response is aligned with the request indexes.</summary>
    [JsonPropertyName("items")]
    public required IReadOnlyList<PayoutLinkBatchItemsItem> Items { get; init; }
}

/// <summary>One item of <c>items</c> in <c>POST /v1/payout/link/batch</c>.</summary>
public sealed record PayoutLinkBatchItemsItem
{
    /// <summary>Amount in currency, as a string; greater than zero. Decimal string, never a float. Example: <c>"25"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Payout crypto asset (USDT, BTC, …); fiat is not possible. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>If set, the recipient receives an email with a "Claim funds" button; a delivery failure does not cancel link creation. Example: <c>"user@example.com"</c>.</summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>Link lifetime in seconds, clamped to 3600–2592000 (one hour to 30 days); without the field or with 0 the link lives 1 hour, not the maximum — set it explicitly. Example: <c>604800</c>.</summary>
    [JsonPropertyName("expires_in_seconds")]
    public int? ExpiresInSeconds { get; init; }

    /// <summary>Who pays the network fee: "recipient" (default — deducted from the amount, the recipient receives less) or "merchant" (the amount plus the fee is reserved, the recipient receives exactly amount). Example: <c>"merchant"</c>.</summary>
    [JsonPropertyName("fee_bearer")]
    public FeeBearer? FeeBearer { get; init; }

    /// <summary>Payout network for the recipient (tron, bitcoin, …). Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public required Network Network { get; init; }

    /// <summary>Message to the recipient (shown on the claim page and in the email).</summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }

    /// <summary>Claim code — a second factor for the link: "auto" — we generate it and return it ONCE in the response, or your own (6–64 visible characters), empty — no code. Pass the code to the recipient over a channel SEPARATE from the link (it is not put into the email); after 10 incorrect attempts the link is locked. Example: <c>"auto"</c>.</summary>
    [JsonPropertyName("passcode")]
    public string? Passcode { get; init; }

    /// <summary>Your deduplication key, unique per merchant; the Idempotency-Key header has no effect on this endpoint. Example: <c>"bonus-42"</c>.</summary>
    [JsonPropertyName("reference")]
    public required string Reference { get; init; }

    /// <summary>Title — shown to the recipient on the claim page.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/link/cancel</c>.</summary>
public sealed record PayoutLinkCancelRequest
{
    /// <summary>Payout link id (link_id from the creation response).</summary>
    [JsonPropertyName("link_id")]
    public required string LinkId { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/link/cheque</c>.</summary>
public sealed record PayoutLinkChequeRequest
{
    /// <summary>Claim secret from the payout link creation response. Stored only as a hash and never reissued — the cheque can be printed only while you still hold the token.</summary>
    [JsonPropertyName("claim_token")]
    public required string ClaimToken { get; init; }

    /// <summary>Document language — one of the 41 supported codes (en by default); the full list is in the document.unknown_lang error. Example: <c>"ru"</c>.</summary>
    [JsonPropertyName("lang")]
    public string? Lang { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/link/info</c>.</summary>
public sealed record PayoutLinkInfoRequest
{
    /// <summary>Payout link id (link_id from the creation response).</summary>
    [JsonPropertyName("link_id")]
    public required string LinkId { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/link/list</c>.</summary>
public sealed record PayoutLinkListRequest
{
    /// <summary>How many links to return per page. Example: <c>50</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (paging). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/mass</c>.</summary>
public sealed record PayoutMassRequest
{
    /// <summary>Array of up to 100 items; the fields of each are as in POST /v1/payout.</summary>
    [JsonPropertyName("payouts")]
    public required IReadOnlyList<PayoutMassPayoutsItem> Payouts { get; init; }

    /// <summary>Origin label, applied to every item without its own source.</summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }
}

/// <summary>One item of <c>payouts</c> in <c>POST /v1/payout/mass</c>.</summary>
public sealed record PayoutMassPayoutsItem
{
    /// <summary>Recipient address.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Payout amount, in currency. Decimal string, never a float. Example: <c>"25"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (for example USDT). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Fund the payout by converting the balance. USDT → currency only. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("from_currency")]
    public string? FromCurrency { get; init; }

    /// <summary>Who pays the network fee: true — amount+fee is debited from the balance and the recipient receives amount; false — the recipient receives amount-fee; not provided — the project fee-config.</summary>
    [JsonPropertyName("is_subtract")]
    public bool? IsSubtract { get; init; }

    /// <summary>Destination tag/memo (TON Jetton). Maximum 120 characters.</summary>
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }

    /// <summary>Network (tron, ethereum, …). Required for coins with several networks. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your payout number; idempotency key. Example: <c>"payout-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>Origin label: api (default) or manual.</summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST /v1/webhooks): delivery is signed with its secret.</summary>
    [JsonPropertyName("url_callback")]
    public string? UrlCallback { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/refund-fee-config/set</c>.</summary>
public sealed record PayoutRefundFeeConfigSetRequest
{
    /// <summary>true — the customer receives net (the customer pays the fee); false — the merchant pays the fee and the customer receives gross. Example: <c>true</c>.</summary>
    [JsonPropertyName("fee_on_customer")]
    public required bool FeeOnCustomer { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/services</c>.</summary>
public sealed record PayoutServicesRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/payout/validate</c>.</summary>
public sealed record PayoutValidateRequest
{
    /// <summary>Recipient address.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Payout amount, in currency. Decimal string, never a float. Example: <c>"25"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (for example USDT). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Fund the payout by converting the balance. USDT → currency only. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("from_currency")]
    public string? FromCurrency { get; init; }

    /// <summary>Who pays the network fee: true — amount+fee is debited from the balance and the recipient receives amount; false — the recipient receives amount-fee; not provided — the project fee-config.</summary>
    [JsonPropertyName("is_subtract")]
    public bool? IsSubtract { get; init; }

    /// <summary>Destination tag/memo (TON Jetton). Maximum 120 characters.</summary>
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }

    /// <summary>Network (tron, ethereum, …). Required for coins with several networks. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your payout number; idempotency key. Example: <c>"payout-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Origin label: api (default) or manual.</summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST /v1/webhooks): delivery is signed with its secret.</summary>
    [JsonPropertyName("url_callback")]
    public string? UrlCallback { get; init; }
}

/// <summary>Request body of <c>POST /v1/refund/batch</c>.</summary>
public sealed record RefundBatchRequest
{
    /// <summary>What to do when an item fails: continue (default) — process the rest; stop — halt processing after the first error. Example: <c>"continue"</c>.</summary>
    [JsonPropertyName("on_error")]
    public BatchOnError? OnError { get; init; }

    /// <summary>Array of 1 to 5000 items — the same fields as POST /v1/payment/refund; every item requires reference (idempotency key) and either uuid or order_id of the payment.</summary>
    [JsonPropertyName("refunds")]
    public required IReadOnlyList<RefundBatchRefundsItem> Refunds { get; init; }
}

/// <summary>One item of <c>refunds</c> in <c>POST /v1/refund/batch</c>.</summary>
public sealed record RefundBatchRefundsItem
{
    /// <summary>Refund destination address. Defaults to the payment's payer_address; required only for Bitcoin/UTXO.</summary>
    [JsonPropertyName("address")]
    public string? Address { get; init; }

    /// <summary>Partial amount. Defaults to the full amount received. Decimal string, never a float. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; init; }

    /// <summary>Network. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your order reference for the payment. Either uuid or order_id is required. Example: <c>"order-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Optional refund idempotency key: distinguishes two different refunds with the same (payment, address, amount); a repeat with the same value is deduplicated. This is not order_id.</summary>
    [JsonPropertyName("reference")]
    public required string Reference { get; init; }

    /// <summary>Payment id. Either uuid or order_id is required.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/sandbox/deposit</c>.</summary>
public sealed record SandboxDepositRequest
{
    /// <summary>Amount in the invoice currency; empty — pay exactly what is due, anything else is a way to produce an under/overpayment. Decimal string, never a float. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; init; }

    /// <summary>How many confirmations the deposit arrived with; 0 — fully confirmed; fewer than required — a way to test the pending→confirmed transition (repeat the same txid with a higher number). Example: <c>0</c>.</summary>
    [JsonPropertyName("confirmations")]
    public int? Confirmations { get; init; }

    /// <summary>UUID of the test invoice being "paid".</summary>
    [JsonPropertyName("invoice_id")]
    public required string InvoiceId { get; init; }

    /// <summary>Repeating the same txid tests your idempotency; empty — a new txid.</summary>
    [JsonPropertyName("txid")]
    public string? Txid { get; init; }
}

/// <summary>Request body of <c>POST /v1/sandbox/faucet</c>.</summary>
public sealed record SandboxFaucetRequest
{
    /// <summary>Amount of test money, as a string; capped at 1000000 per call. Decimal string, never a float. Example: <c>"1000"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Top-up asset (USDT, BTC, …). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("asset")]
    public required string Asset { get; init; }

    /// <summary>Safe-retry key; empty — every call creates a new top-up.</summary>
    [JsonPropertyName("idempotency_key")]
    public string? IdempotencyKey { get; init; }
}

/// <summary>Request body of <c>POST /v1/sandbox/webhooks/replay</c>.</summary>
public sealed record SandboxWebhooksReplayRequest
{
    /// <summary>Delivery id from GET /v1/sandbox/webhooks.</summary>
    [JsonPropertyName("delivery_id")]
    public required string DeliveryId { get; init; }
}

/// <summary>Request body of <c>POST /v1/split/config/set</c>.</summary>
public sealed record SplitConfigSetRequest
{
    /// <summary>How many seconds to defer split settlement; range 0–7776000 (up to 90 days). 0 — send the shares immediately: you take on the risk that a refund becomes impossible. Example: <c>172800</c>.</summary>
    [JsonPropertyName("refund_hold_seconds")]
    public required int RefundHoldSeconds { get; init; }
}

/// <summary>Request body of <c>POST /v1/split/recipient/optin</c>.</summary>
public sealed record SplitRecipientOptinRequest
{
    /// <summary>Allow other merchants to route split shares to your balance. true — enable receiving, false — disable (new rules targeting you stop being created; existing ones keep executing). Example: <c>true</c>.</summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }
}

/// <summary>Request body of <c>POST /v1/split/rule</c>.</summary>
public sealed record SplitRuleRequest
{
    /// <summary>External crypto address of the partner; the share leaves as a real on-chain transaction — irreversible. Exactly one recipient option: either address+network or merchant_id.</summary>
    [JsonPropertyName("address")]
    public string? Address { get; init; }

    /// <summary>Id of the partner merchant inside Oblodai; the share moves through internal accounting and is clawed back on a refund. Example: <c>"b4c1f0e2-5a77-4d31-9f08-2c6e7a1b3d94"</c>.</summary>
    [JsonPropertyName("merchant_id")]
    public string? MerchantId { get; init; }

    /// <summary>Address network. Required together with address. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Comment for yourself (shown in the rule list).</summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }

    /// <summary>Share of every payment, as a string: "10" = 10 %, "2.5" = 2.5 %. Greater than 0 and at most 100, step 0.01 %; the sum of all rules cannot exceed 100 %. Example: <c>"10"</c>.</summary>
    [JsonPropertyName("percent")]
    public required string Percent { get; init; }
}

/// <summary>Request body of <c>POST /v1/split/rule/delete</c>.</summary>
public sealed record SplitRuleDeleteRequest
{
    /// <summary>Rule identifier from POST /v1/split/rule or the list. Example: <c>"9f4c1a2b-77de-4a55-9c1f-0e2b3d4a5f60"</c>.</summary>
    [JsonPropertyName("rule_id")]
    public required string RuleId { get; init; }
}

/// <summary>Request body of <c>POST /v1/split/rule/list</c>.</summary>
public sealed record SplitRuleListRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

/// <summary>Request body of <c>POST /v1/test-webhook/payment</c>.</summary>
public sealed record TestWebhookPaymentRequest
{
    /// <summary>Currency in the body. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Network in the body. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your order_id, which is put into the test event body.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Status in the body — from the status dictionary of this event type. Default paid (confirmed for a payout). Example: <c>"paid"</c>.</summary>
    [JsonPropertyName("status")]
    public PaymentStatus? Status { get; init; }

    /// <summary>Where to send the test body. Example: <c>"https://shop.example/oblodai/callback"</c>.</summary>
    [JsonPropertyName("url_callback")]
    public required string UrlCallback { get; init; }

    /// <summary>UUID of the object (payment, wallet or payout) put into the test event body.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/test-webhook/payout</c>.</summary>
public sealed record TestWebhookPayoutRequest
{
    /// <summary>Currency in the body. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Network in the body. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your order_id, which is put into the test event body.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Status in the body — from the status dictionary of this event type. Default paid (confirmed for a payout). Example: <c>"paid"</c>.</summary>
    [JsonPropertyName("status")]
    public PayoutStatus? Status { get; init; }

    /// <summary>Where to send the test body. Example: <c>"https://shop.example/oblodai/callback"</c>.</summary>
    [JsonPropertyName("url_callback")]
    public required string UrlCallback { get; init; }

    /// <summary>UUID of the object (payment, wallet or payout) put into the test event body.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/test-webhook/wallet</c>.</summary>
public sealed record TestWebhookWalletRequest
{
    /// <summary>Currency in the body. Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Network in the body. Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>Your order_id, which is put into the test event body.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Status in the body — from the status dictionary of this event type. Default paid (confirmed for a payout). Always <c>paid</c>. Example: <c>"paid"</c>.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; init; }

    /// <summary>Where to send the test body. Example: <c>"https://shop.example/oblodai/callback"</c>.</summary>
    [JsonPropertyName("url_callback")]
    public required string UrlCallback { get; init; }

    /// <summary>UUID of the object (payment, wallet or payout) put into the test event body.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/transfer/batch</c>.</summary>
public sealed record TransferBatchRequest
{
    /// <summary>What to do when an item fails: continue (default) — process the rest; stop — halt processing after the first error. Example: <c>"continue"</c>.</summary>
    [JsonPropertyName("on_error")]
    public BatchOnError? OnError { get; init; }

    /// <summary>Array of 1 to 5000 items — the same fields as POST /v1/transfer/to-user; every item requires order_id (idempotency key) and to_user_id (user UUID).</summary>
    [JsonPropertyName("transfers")]
    public IReadOnlyList<TransferBatchTransfersItem>? Transfers { get; init; }
}

/// <summary>One item of <c>transfers</c> in <c>POST /v1/transfer/batch</c>.</summary>
public sealed record TransferBatchTransfersItem
{
    /// <summary>Transfer amount in currency. Decimal string, never a float. Example: <c>"50"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (cryptocurrency). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Idempotency key: a repeat with the same order_id is a no-op; required in a transfer batch.</summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>Platform user id of the recipient (UUID, not username); a username is resolved to an id via the cabinet public profile /public/users/{username}.</summary>
    [JsonPropertyName("to_user_id")]
    public required string ToUserId { get; init; }
}

/// <summary>Request body of <c>POST /v1/transfer/to-personal</c>.</summary>
public sealed record TransferToPersonalRequest
{
    /// <summary>Transfer amount in currency. Decimal string, never a float. Example: <c>"50"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (cryptocurrency). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Idempotency key: a repeat with the same order_id is a no-op. Always send it, otherwise retrying the request after a network timeout creates a second transfer. Example: <c>"transfer-1"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }
}

/// <summary>Request body of <c>POST /v1/transfer/to-user</c>.</summary>
public sealed record TransferToUserRequest
{
    /// <summary>Transfer amount in currency. Decimal string, never a float. Example: <c>"50"</c>.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; init; }

    /// <summary>Currency code (cryptocurrency). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Idempotency key: a repeat with the same order_id is a no-op; required in a transfer batch.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }

    /// <summary>Platform user id of the recipient (UUID, not username); a username is resolved to an id via the cabinet public profile /public/users/{username}.</summary>
    [JsonPropertyName("to_user_id")]
    public required string ToUserId { get; init; }
}

/// <summary>Request body of <c>POST /v1/vrcs</c>.</summary>
public sealed record VrcsRequest
{
    /// <summary>true — enable auto-conversion of volatile deposits to USDT, false — disable; omit to read the current state. Example: <c>true</c>.</summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }
}

/// <summary>Request body of <c>POST /v1/wallet</c>.</summary>
public sealed record WalletRequest
{
    /// <summary>Symbol of the receiving currency (USDT, BTC, ETH, …). Example: <c>"USDT"</c>.</summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>Receiving network (tron, ethereum, bitcoin, …). Example: <c>"tron"</c>.</summary>
    [JsonPropertyName("network")]
    public required Network Network { get; init; }

    /// <summary>Your customer/order identifier. Pins a dedicated permanent address to the customer. Example: <c>"client-42"</c>.</summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; init; }
}

/// <summary>Request body of <c>POST /v1/wallet/block</c>.</summary>
public sealed record WalletBlockRequest
{
    /// <summary>Static wallet address. Example: <c>"TXk9...c3Fd"</c>.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>true — block (the default when the field is omitted); false — unblock.</summary>
    [JsonPropertyName("is_force_block")]
    public bool? IsForceBlock { get; init; }
}

/// <summary>Request body of <c>POST /v1/wallet/blocked-address-refund</c>.</summary>
public sealed record WalletBlockedAddressRefundRequest
{
    /// <summary>Refund destination address.</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }

    /// <summary>Destination tag/memo (XRP destination tag, XLM memo id, TON comment). Required for a classic address on a tag/memo network if the tag is not embedded in the X-/M-address.</summary>
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }

    /// <summary>Static wallet id (from the /v1/wallet response).</summary>
    [JsonPropertyName("uuid")]
    public required string Uuid { get; init; }
}

/// <summary>Request body of <c>POST /v1/wallet/qr</c>.</summary>
public sealed record WalletQrRequest
{
    /// <summary>Arbitrary address to render into a QR code (PNG as a data: URI).</summary>
    [JsonPropertyName("address")]
    public required string Address { get; init; }
}

/// <summary>Request body of <c>POST /v1/webhooks</c>.</summary>
public sealed record WebhooksRequest
{
    /// <summary>HTTPS callback URL. SSRF check: private and local addresses are rejected. Example: <c>"https://shop.example/oblodai/callback"</c>.</summary>
    [JsonPropertyName("url")]
    public required string Url { get; init; }
}

/// <summary>Request body of <c>POST /v1/webhooks/deliveries</c>.</summary>
public sealed record WebhooksDeliveriesRequest
{
    /// <summary>Page size, 1–100; out of range falls back to 25. Example: <c>25</c>.</summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>Offset from the start of the list (newest first). Example: <c>0</c>.</summary>
    [JsonPropertyName("offset")]
    public int? Offset { get; init; }
}

