// <auto-generated />
// GENERATED FILE — do not edit. Source: contract/contract.json (core 2cc44c16f516).
// Regenerate with: dotnet run --project tools/Codegen -- generate

#nullable enable

namespace Oblodai.Contract;

/// <summary>
/// Every merchant-facing route the gateway declares, keyed exactly as its conformance table keys
/// them. This registry is the SDK's coverage ledger: a route the gateway adds shows up here on the
/// next codegen run and the contract tests fail until a method is wired to it.
/// </summary>
public static class Routes
{
    /// <summary><c>POST /v1/api-allowlist/add</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1ApiAllowlistAdd = new("POST", "/v1/api-allowlist/add", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.Plain);

    /// <summary><c>POST /v1/api-allowlist/enable</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1ApiAllowlistEnable = new("POST", "/v1/api-allowlist/enable", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.Plain);

    /// <summary><c>POST /v1/api-allowlist/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1ApiAllowlistList = new("POST", "/v1/api-allowlist/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Plain);

    /// <summary><c>POST /v1/api-allowlist/remove</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1ApiAllowlistRemove = new("POST", "/v1/api-allowlist/remove", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.Plain);

    /// <summary><c>POST /v1/auto-withdraw/delete</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1AutoWithdrawDelete = new("POST", "/v1/auto-withdraw/delete", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/auto-withdraw/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1AutoWithdrawList = new("POST", "/v1/auto-withdraw/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Plain);

    /// <summary><c>POST /v1/auto-withdraw/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1AutoWithdrawSet = new("POST", "/v1/auto-withdraw/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/balance</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1Balance = new("POST", "/v1/balance", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/batch/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1BatchInfo = new("POST", "/v1/batch/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/claim/{token}</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec GetV1ClaimToken = new("GET", "/v1/claim/{token}", RouteAuth.Public, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/claim/{token}</c> — no credentials.</summary>
    public static readonly RouteSpec PostV1ClaimToken = new("POST", "/v1/claim/{token}", RouteAuth.Public, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/currencies</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec GetV1Currencies = new("GET", "/v1/currencies", RouteAuth.Public, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/documents/balance</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsBalance = new("GET", "/v1/documents/balance", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/batch</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsBatch = new("GET", "/v1/documents/batch", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/fees</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsFees = new("GET", "/v1/documents/fees", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>POST /v1/documents/jobs</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1DocumentsJobs = new("POST", "/v1/documents/jobs", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/documents/jobs/file</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsJobsFile = new("GET", "/v1/documents/jobs/file", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>POST /v1/documents/jobs/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1DocumentsJobsInfo = new("POST", "/v1/documents/jobs/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/documents/ledger</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsLedger = new("GET", "/v1/documents/ledger", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/link</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsLink = new("GET", "/v1/documents/link", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/referrals</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsReferrals = new("GET", "/v1/documents/referrals", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/split</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsSplit = new("GET", "/v1/documents/split", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/statement</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsStatement = new("GET", "/v1/documents/statement", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/wallet/statement</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsWalletStatement = new("GET", "/v1/documents/wallet/statement", RouteAuth.Key, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>GET /v1/documents/{kind}/{id}</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec GetV1DocumentsKindId = new("GET", "/v1/documents/{kind}/{id}", RouteAuth.Public, Idempotent: false, Safe: true, Bare: true, List: ListKind.None);

    /// <summary><c>POST /v1/exchange-rate/list</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec PostV1ExchangeRateList = new("POST", "/v1/exchange-rate/list", RouteAuth.Public, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>GET /v1/link/{id}</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec GetV1LinkId = new("GET", "/v1/link/{id}", RouteAuth.Public, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/link/{id}/checkout</c> — no credentials.</summary>
    public static readonly RouteSpec PostV1LinkIdCheckout = new("POST", "/v1/link/{id}/checkout", RouteAuth.Public, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/merchants</c> — unsigned provisioning route.</summary>
    public static readonly RouteSpec PostV1Merchants = new("POST", "/v1/merchants", RouteAuth.Onboard, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/merchants/{id}/sandbox</c> — unsigned provisioning route.</summary>
    public static readonly RouteSpec PostV1MerchantsIdSandbox = new("POST", "/v1/merchants/{id}/sandbox", RouteAuth.Onboard, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/pay/{id}</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec GetV1PayId = new("GET", "/v1/pay/{id}", RouteAuth.Public, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/pay/{id}/qr</c> — no credentials, read-only.</summary>
    public static readonly RouteSpec GetV1PayIdQr = new("GET", "/v1/pay/{id}/qr", RouteAuth.Public, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/pay/{id}/select</c> — no credentials.</summary>
    public static readonly RouteSpec PostV1PayIdSelect = new("POST", "/v1/pay/{id}/select", RouteAuth.Public, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1Payment = new("POST", "/v1/payment", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/accepted/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentAcceptedList = new("POST", "/v1/payment/accepted/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payment/accepted/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentAcceptedSet = new("POST", "/v1/payment/accepted/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/accuracy/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentAccuracyGet = new("POST", "/v1/payment/accuracy/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/accuracy/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentAccuracySet = new("POST", "/v1/payment/accuracy/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/autorefund/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentAutorefundGet = new("POST", "/v1/payment/autorefund/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/autorefund/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentAutorefundSet = new("POST", "/v1/payment/autorefund/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/batch</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PaymentBatch = new("POST", "/v1/payment/batch", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/cancel</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentCancel = new("POST", "/v1/payment/cancel", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/discount/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentDiscountList = new("POST", "/v1/payment/discount/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payment/discount/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentDiscountSet = new("POST", "/v1/payment/discount/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/fee-config/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentFeeConfigGet = new("POST", "/v1/payment/fee-config/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/fee-config/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentFeeConfigSet = new("POST", "/v1/payment/fee-config/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/history</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentHistory = new("POST", "/v1/payment/history", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payment/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentInfo = new("POST", "/v1/payment/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/link</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentLink = new("POST", "/v1/payment/link", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/link/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentLinkInfo = new("POST", "/v1/payment/link/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/link/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentLinkList = new("POST", "/v1/payment/link/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payment/link/toggle</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentLinkToggle = new("POST", "/v1/payment/link/toggle", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/qr</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentQr = new("POST", "/v1/payment/qr", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/refund</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PaymentRefund = new("POST", "/v1/payment/refund", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/resend</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentResend = new("POST", "/v1/payment/resend", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/resolve</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PaymentResolve = new("POST", "/v1/payment/resolve", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/send-email</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentSendEmail = new("POST", "/v1/payment/send-email", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payment/services</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PaymentServices = new("POST", "/v1/payment/services", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payment/testing-webhook</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PaymentTestingWebhook = new("POST", "/v1/payment/testing-webhook", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1Payout = new("POST", "/v1/payout", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/approve</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PayoutApprove = new("POST", "/v1/payout/approve", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/batch</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PayoutBatch = new("POST", "/v1/payout/batch", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/calculate</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutCalculate = new("POST", "/v1/payout/calculate", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/cancel</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PayoutCancel = new("POST", "/v1/payout/cancel", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/fee-config/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutFeeConfigGet = new("POST", "/v1/payout/fee-config/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/fee-config/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PayoutFeeConfigSet = new("POST", "/v1/payout/fee-config/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/history</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutHistory = new("POST", "/v1/payout/history", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payout/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutInfo = new("POST", "/v1/payout/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/link</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PayoutLink = new("POST", "/v1/payout/link", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/link/batch</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PayoutLinkBatch = new("POST", "/v1/payout/link/batch", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/link/cancel</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PayoutLinkCancel = new("POST", "/v1/payout/link/cancel", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/link/cheque</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PayoutLinkCheque = new("POST", "/v1/payout/link/cheque", RouteAuth.Key, Idempotent: false, Safe: false, Bare: true, List: ListKind.None);

    /// <summary><c>POST /v1/payout/link/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutLinkInfo = new("POST", "/v1/payout/link/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/link/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutLinkList = new("POST", "/v1/payout/link/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payout/mass</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1PayoutMass = new("POST", "/v1/payout/mass", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/refund-fee-config/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutRefundFeeConfigGet = new("POST", "/v1/payout/refund-fee-config/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/refund-fee-config/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1PayoutRefundFeeConfigSet = new("POST", "/v1/payout/refund-fee-config/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/payout/services</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutServices = new("POST", "/v1/payout/services", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/payout/validate</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1PayoutValidate = new("POST", "/v1/payout/validate", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/referral/info</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1ReferralInfo = new("POST", "/v1/referral/info", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/refund/batch</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1RefundBatch = new("POST", "/v1/refund/batch", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/sandbox/deposit</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SandboxDeposit = new("POST", "/v1/sandbox/deposit", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/sandbox/faucet</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SandboxFaucet = new("POST", "/v1/sandbox/faucet", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/sandbox/reset</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SandboxReset = new("POST", "/v1/sandbox/reset", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>GET /v1/sandbox/webhooks</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec GetV1SandboxWebhooks = new("GET", "/v1/sandbox/webhooks", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/sandbox/webhooks/replay</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SandboxWebhooksReplay = new("POST", "/v1/sandbox/webhooks/replay", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/config/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1SplitConfigGet = new("POST", "/v1/split/config/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/config/set</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SplitConfigSet = new("POST", "/v1/split/config/set", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/recipient/optin</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SplitRecipientOptin = new("POST", "/v1/split/recipient/optin", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/recipient/optin/get</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1SplitRecipientOptinGet = new("POST", "/v1/split/recipient/optin/get", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/rule</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1SplitRule = new("POST", "/v1/split/rule", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/rule/delete</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1SplitRuleDelete = new("POST", "/v1/split/rule/delete", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/split/rule/list</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1SplitRuleList = new("POST", "/v1/split/rule/list", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/test-webhook/payment</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1TestWebhookPayment = new("POST", "/v1/test-webhook/payment", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/test-webhook/payout</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1TestWebhookPayout = new("POST", "/v1/test-webhook/payout", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/test-webhook/wallet</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1TestWebhookWallet = new("POST", "/v1/test-webhook/wallet", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/transfer/batch</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1TransferBatch = new("POST", "/v1/transfer/batch", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/transfer/to-personal</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1TransferToPersonal = new("POST", "/v1/transfer/to-personal", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/transfer/to-user</c> — signed with the API key, deduplicated by Idempotency-Key.</summary>
    public static readonly RouteSpec PostV1TransferToUser = new("POST", "/v1/transfer/to-user", RouteAuth.Key, Idempotent: true, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/vrcs</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1Vrcs = new("POST", "/v1/vrcs", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/wallet</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1Wallet = new("POST", "/v1/wallet", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/wallet/block</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1WalletBlock = new("POST", "/v1/wallet/block", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/wallet/blocked-address-refund</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1WalletBlockedAddressRefund = new("POST", "/v1/wallet/blocked-address-refund", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/wallet/qr</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1WalletQr = new("POST", "/v1/wallet/qr", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/webhooks</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1Webhooks = new("POST", "/v1/webhooks", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary><c>POST /v1/webhooks/deliveries</c> — signed with the API key, read-only.</summary>
    public static readonly RouteSpec PostV1WebhooksDeliveries = new("POST", "/v1/webhooks/deliveries", RouteAuth.Key, Idempotent: false, Safe: true, Bare: false, List: ListKind.Paged);

    /// <summary><c>POST /v1/webhooks/rotate-secret</c> — signed with the API key.</summary>
    public static readonly RouteSpec PostV1WebhooksRotateSecret = new("POST", "/v1/webhooks/rotate-secret", RouteAuth.Key, Idempotent: false, Safe: false, Bare: false, List: ListKind.None);

    /// <summary>The whole registry, by route key.</summary>
    public static readonly IReadOnlyDictionary<string, RouteSpec> All =
        new Dictionary<string, RouteSpec>(StringComparer.Ordinal)
        {
            ["POST /v1/api-allowlist/add"] = PostV1ApiAllowlistAdd,
            ["POST /v1/api-allowlist/enable"] = PostV1ApiAllowlistEnable,
            ["POST /v1/api-allowlist/list"] = PostV1ApiAllowlistList,
            ["POST /v1/api-allowlist/remove"] = PostV1ApiAllowlistRemove,
            ["POST /v1/auto-withdraw/delete"] = PostV1AutoWithdrawDelete,
            ["POST /v1/auto-withdraw/list"] = PostV1AutoWithdrawList,
            ["POST /v1/auto-withdraw/set"] = PostV1AutoWithdrawSet,
            ["POST /v1/balance"] = PostV1Balance,
            ["POST /v1/batch/info"] = PostV1BatchInfo,
            ["GET /v1/claim/{token}"] = GetV1ClaimToken,
            ["POST /v1/claim/{token}"] = PostV1ClaimToken,
            ["GET /v1/currencies"] = GetV1Currencies,
            ["GET /v1/documents/balance"] = GetV1DocumentsBalance,
            ["GET /v1/documents/batch"] = GetV1DocumentsBatch,
            ["GET /v1/documents/fees"] = GetV1DocumentsFees,
            ["POST /v1/documents/jobs"] = PostV1DocumentsJobs,
            ["GET /v1/documents/jobs/file"] = GetV1DocumentsJobsFile,
            ["POST /v1/documents/jobs/info"] = PostV1DocumentsJobsInfo,
            ["GET /v1/documents/ledger"] = GetV1DocumentsLedger,
            ["GET /v1/documents/link"] = GetV1DocumentsLink,
            ["GET /v1/documents/referrals"] = GetV1DocumentsReferrals,
            ["GET /v1/documents/split"] = GetV1DocumentsSplit,
            ["GET /v1/documents/statement"] = GetV1DocumentsStatement,
            ["GET /v1/documents/wallet/statement"] = GetV1DocumentsWalletStatement,
            ["GET /v1/documents/{kind}/{id}"] = GetV1DocumentsKindId,
            ["POST /v1/exchange-rate/list"] = PostV1ExchangeRateList,
            ["GET /v1/link/{id}"] = GetV1LinkId,
            ["POST /v1/link/{id}/checkout"] = PostV1LinkIdCheckout,
            ["POST /v1/merchants"] = PostV1Merchants,
            ["POST /v1/merchants/{id}/sandbox"] = PostV1MerchantsIdSandbox,
            ["GET /v1/pay/{id}"] = GetV1PayId,
            ["GET /v1/pay/{id}/qr"] = GetV1PayIdQr,
            ["POST /v1/pay/{id}/select"] = PostV1PayIdSelect,
            ["POST /v1/payment"] = PostV1Payment,
            ["POST /v1/payment/accepted/list"] = PostV1PaymentAcceptedList,
            ["POST /v1/payment/accepted/set"] = PostV1PaymentAcceptedSet,
            ["POST /v1/payment/accuracy/get"] = PostV1PaymentAccuracyGet,
            ["POST /v1/payment/accuracy/set"] = PostV1PaymentAccuracySet,
            ["POST /v1/payment/autorefund/get"] = PostV1PaymentAutorefundGet,
            ["POST /v1/payment/autorefund/set"] = PostV1PaymentAutorefundSet,
            ["POST /v1/payment/batch"] = PostV1PaymentBatch,
            ["POST /v1/payment/cancel"] = PostV1PaymentCancel,
            ["POST /v1/payment/discount/list"] = PostV1PaymentDiscountList,
            ["POST /v1/payment/discount/set"] = PostV1PaymentDiscountSet,
            ["POST /v1/payment/fee-config/get"] = PostV1PaymentFeeConfigGet,
            ["POST /v1/payment/fee-config/set"] = PostV1PaymentFeeConfigSet,
            ["POST /v1/payment/history"] = PostV1PaymentHistory,
            ["POST /v1/payment/info"] = PostV1PaymentInfo,
            ["POST /v1/payment/link"] = PostV1PaymentLink,
            ["POST /v1/payment/link/info"] = PostV1PaymentLinkInfo,
            ["POST /v1/payment/link/list"] = PostV1PaymentLinkList,
            ["POST /v1/payment/link/toggle"] = PostV1PaymentLinkToggle,
            ["POST /v1/payment/qr"] = PostV1PaymentQr,
            ["POST /v1/payment/refund"] = PostV1PaymentRefund,
            ["POST /v1/payment/resend"] = PostV1PaymentResend,
            ["POST /v1/payment/resolve"] = PostV1PaymentResolve,
            ["POST /v1/payment/send-email"] = PostV1PaymentSendEmail,
            ["POST /v1/payment/services"] = PostV1PaymentServices,
            ["POST /v1/payment/testing-webhook"] = PostV1PaymentTestingWebhook,
            ["POST /v1/payout"] = PostV1Payout,
            ["POST /v1/payout/approve"] = PostV1PayoutApprove,
            ["POST /v1/payout/batch"] = PostV1PayoutBatch,
            ["POST /v1/payout/calculate"] = PostV1PayoutCalculate,
            ["POST /v1/payout/cancel"] = PostV1PayoutCancel,
            ["POST /v1/payout/fee-config/get"] = PostV1PayoutFeeConfigGet,
            ["POST /v1/payout/fee-config/set"] = PostV1PayoutFeeConfigSet,
            ["POST /v1/payout/history"] = PostV1PayoutHistory,
            ["POST /v1/payout/info"] = PostV1PayoutInfo,
            ["POST /v1/payout/link"] = PostV1PayoutLink,
            ["POST /v1/payout/link/batch"] = PostV1PayoutLinkBatch,
            ["POST /v1/payout/link/cancel"] = PostV1PayoutLinkCancel,
            ["POST /v1/payout/link/cheque"] = PostV1PayoutLinkCheque,
            ["POST /v1/payout/link/info"] = PostV1PayoutLinkInfo,
            ["POST /v1/payout/link/list"] = PostV1PayoutLinkList,
            ["POST /v1/payout/mass"] = PostV1PayoutMass,
            ["POST /v1/payout/refund-fee-config/get"] = PostV1PayoutRefundFeeConfigGet,
            ["POST /v1/payout/refund-fee-config/set"] = PostV1PayoutRefundFeeConfigSet,
            ["POST /v1/payout/services"] = PostV1PayoutServices,
            ["POST /v1/payout/validate"] = PostV1PayoutValidate,
            ["POST /v1/referral/info"] = PostV1ReferralInfo,
            ["POST /v1/refund/batch"] = PostV1RefundBatch,
            ["POST /v1/sandbox/deposit"] = PostV1SandboxDeposit,
            ["POST /v1/sandbox/faucet"] = PostV1SandboxFaucet,
            ["POST /v1/sandbox/reset"] = PostV1SandboxReset,
            ["GET /v1/sandbox/webhooks"] = GetV1SandboxWebhooks,
            ["POST /v1/sandbox/webhooks/replay"] = PostV1SandboxWebhooksReplay,
            ["POST /v1/split/config/get"] = PostV1SplitConfigGet,
            ["POST /v1/split/config/set"] = PostV1SplitConfigSet,
            ["POST /v1/split/recipient/optin"] = PostV1SplitRecipientOptin,
            ["POST /v1/split/recipient/optin/get"] = PostV1SplitRecipientOptinGet,
            ["POST /v1/split/rule"] = PostV1SplitRule,
            ["POST /v1/split/rule/delete"] = PostV1SplitRuleDelete,
            ["POST /v1/split/rule/list"] = PostV1SplitRuleList,
            ["POST /v1/test-webhook/payment"] = PostV1TestWebhookPayment,
            ["POST /v1/test-webhook/payout"] = PostV1TestWebhookPayout,
            ["POST /v1/test-webhook/wallet"] = PostV1TestWebhookWallet,
            ["POST /v1/transfer/batch"] = PostV1TransferBatch,
            ["POST /v1/transfer/to-personal"] = PostV1TransferToPersonal,
            ["POST /v1/transfer/to-user"] = PostV1TransferToUser,
            ["POST /v1/vrcs"] = PostV1Vrcs,
            ["POST /v1/wallet"] = PostV1Wallet,
            ["POST /v1/wallet/block"] = PostV1WalletBlock,
            ["POST /v1/wallet/blocked-address-refund"] = PostV1WalletBlockedAddressRefund,
            ["POST /v1/wallet/qr"] = PostV1WalletQr,
            ["POST /v1/webhooks"] = PostV1Webhooks,
            ["POST /v1/webhooks/deliveries"] = PostV1WebhooksDeliveries,
            ["POST /v1/webhooks/rotate-secret"] = PostV1WebhooksRotateSecret,
        };
}
