using System.Security.Cryptography;
using System.Text;

namespace Oblodai.Codegen;

/// <summary>Emits the route registry, the open vocabularies, the error codes and the snapshot stamp.</summary>
internal static class Emitters
{
    public static string Header(Contract contract) =>
        $"""
         // <auto-generated />
         // GENERATED FILE — do not edit. Source: contract/contract.json (core {contract.CoreCommit[..12]}).
         // Regenerate with: dotnet run --project tools/Codegen -- generate

         #nullable enable

         """ + Environment.NewLine;

    public static string Routes(Contract contract)
    {
        var output = new StringBuilder(Header(contract));
        output.AppendLine("namespace Oblodai.Contract;");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine("/// Every merchant-facing route the gateway declares, keyed exactly as its conformance table keys");
        output.AppendLine("/// them. This registry is the SDK's coverage ledger: a route the gateway adds shows up here on the");
        output.AppendLine("/// next codegen run and the contract tests fail until a method is wired to it.");
        output.AppendLine("/// </summary>");
        output.AppendLine("public static class Routes");
        output.AppendLine("{");

        var members = new List<(string Member, string Key)>();
        foreach (var route in contract.Routes)
        {
            var member = Naming.RouteMember(route.Method, route.Path);
            members.Add((member, route.Key));
            var auth = Naming.Pascal(route.Auth);
            var list = route.List is null ? "None" : Naming.Pascal(route.List);
            output.AppendLine($"    /// <summary><c>{route.Key}</c> — {AuthNote(route.Auth)}{IdempotencyNote(route)}.</summary>");
            output.AppendLine(
                $"    public static readonly RouteSpec {member} = new(\"{route.Method}\", \"{route.Path}\", "
                + $"RouteAuth.{auth}, Idempotent: {Lower(route.Idempotent)}, Safe: {Lower(route.Safe)}, "
                + $"Bare: {Lower(route.Bare)}, List: ListKind.{list});");
            output.AppendLine();
        }

        var duplicates = members.GroupBy(m => m.Member).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        if (duplicates.Count > 0)
        {
            throw new InvalidOperationException($"route member names collide: {string.Join(", ", duplicates)}");
        }

        output.AppendLine("    /// <summary>The whole registry, by route key.</summary>");
        output.AppendLine("    public static readonly IReadOnlyDictionary<string, RouteSpec> All =");
        output.AppendLine("        new Dictionary<string, RouteSpec>(StringComparer.Ordinal)");
        output.AppendLine("        {");
        foreach (var (member, key) in members)
        {
            output.AppendLine($"            [\"{key}\"] = {member},");
        }

        output.AppendLine("        };");
        output.AppendLine("}");
        return output.ToString();
    }

    public static string Enums(Contract contract)
    {
        var output = new StringBuilder(Header(contract));
        output.AppendLine("using System.Text.Json.Serialization;");
        output.AppendLine();
        output.AppendLine("namespace Oblodai.Contract;");
        output.AppendLine();

        var vocabularies = new (string Name, string Source, string Doc)[]
        {
            ("PaymentStatus", "payment_status",
                "Invoice lifecycle: <c>select → created → confirm_check → paid | paid_over | wrong_amount | expired | cancelled</c>."),
            ("PayoutStatus", "payout_status",
                "Payout lifecycle: <c>pending → approved → awaiting_cosign → broadcasting → sent → confirmed | failed | cancelled</c>."),
            ("PayoutLinkStatus", "payout_link_status", "Payout-link (cheque) lifecycle."),
            ("DeliveryStatus", "delivery_status", "Webhook delivery outcome."),
            ("Network", "network", "Settlement networks the gateway supports."),
            ("FeeBearer", "fee_bearer", "Who is asked to bear the network fee on a request."),
            ("FeeBearerResult", "fee_bearer_result", "Who actually bore the fee on a priced result."),
            ("BatchOnError", "batch_on_error", "What an asynchronous batch does when an item fails."),
            ("WebhookKind", "webhook_kind", "Kinds of test webhook the gateway can deliver."),
            ("ErrorKind", "error_kind", "Error families the gateway maps onto HTTP statuses."),
        };

        foreach (var (name, source, doc) in vocabularies)
        {
            Vocabulary(output, name, doc, contract.Enum(source));
        }

        // Vocabularies the gateway does not export as enums yet; pinned here from its handlers.
        Vocabulary(output, "AmountMode", "How a payment link prices its invoices.", ["fixed", "open", "range"]);
        Vocabulary(
            output,
            "EventType",
            "Webhook event types: <c>invoice.&lt;status&gt;</c>, <c>payout.&lt;status&gt;</c>, <c>wallet.paid</c>.",
            contract.Strings("event_types"));

        return output.ToString();
    }

    public static string ErrorCodes(Contract contract)
    {
        var codes = contract.Strings("error_codes");
        var output = new StringBuilder(Header(contract));
        output.AppendLine("namespace Oblodai.Contract;");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine("/// Every error code the gateway can emit (<c>family.reason</c>). The code is the discriminator of");
        output.AppendLine("/// the error family: switch on <see cref=\"OblodaiException.Code\"/> against these constants.");
        output.AppendLine("/// </summary>");
        output.AppendLine("public static class ErrorCodes");
        output.AppendLine("{");

        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var code in codes)
        {
            var member = Naming.Member(code);
            var candidate = member;
            var suffix = 2;
            while (!used.Add(candidate))
            {
                candidate = member + suffix++;
            }

            output.AppendLine($"    /// <summary><c>{code}</c></summary>");
            output.AppendLine($"    public const string {candidate} = \"{code}\";");
            output.AppendLine();
        }

        output.AppendLine("    /// <summary>Every code this snapshot knows.</summary>");
        output.AppendLine("    public static readonly IReadOnlyList<string> All =");
        output.AppendLine("    [");
        foreach (var chunk in codes.Chunk(4))
        {
            output.AppendLine("        " + string.Join(" ", chunk.Select(c => $"\"{c}\",")));
        }

        output.AppendLine("    ];");
        output.AppendLine("}");
        return output.ToString();
    }

    public static string Version(Contract contract)
    {
        var hash = Convert.ToHexString(SHA256.HashData(contract.RawBytes)).ToLowerInvariant();
        var output = new StringBuilder(Header(contract));
        output.AppendLine("namespace Oblodai.Contract;");
        output.AppendLine();
        output.AppendLine("/// <summary>Which snapshot of the gateway contract this build was generated from.</summary>");
        output.AppendLine("public static class ContractVersion");
        output.AppendLine("{");
        output.AppendLine("    /// <summary>Gateway commit that exported the snapshot.</summary>");
        output.AppendLine($"    public const string CoreCommit = \"{contract.CoreCommit}\";");
        output.AppendLine();
        output.AppendLine("    /// <summary>When the snapshot was exported.</summary>");
        output.AppendLine($"    public const string ExportedAt = \"{contract.ExportedAt}\";");
        output.AppendLine();
        output.AppendLine("    /// <summary>SHA-256 of <c>contract/contract.json</c>.</summary>");
        output.AppendLine($"    public const string Hash = \"{hash}\";");
        output.AppendLine("}");
        return output.ToString();
    }

    private static void Vocabulary(StringBuilder output, string name, string doc, IReadOnlyList<string> values)
    {
        output.AppendLine($"/// <summary>{doc}</summary>");
        output.AppendLine("/// <param name=\"Value\">The wire value; unknown values are carried through unchanged.</param>");
        output.AppendLine($"[JsonConverter(typeof(StringValueJsonConverter<{name}>))]");
        output.AppendLine($"public readonly record struct {name}(string Value) : IStringValue<{name}>");
        output.AppendLine("{");
        foreach (var value in values)
        {
            output.AppendLine($"    /// <summary><c>{value}</c></summary>");
            output.AppendLine($"    public static readonly {name} {Naming.Member(value)} = new(\"{value}\");");
            output.AppendLine();
        }

        output.AppendLine("    /// <summary>Every value this snapshot knows.</summary>");
        output.AppendLine($"    public static readonly IReadOnlyList<{name}> Known =");
        output.AppendLine("    [");
        foreach (var chunk in values.Chunk(6))
        {
            output.AppendLine("        " + string.Join(" ", chunk.Select(v => $"{Naming.Member(v)},")));
        }

        output.AppendLine("    ];");
        output.AppendLine();
        output.AppendLine("    /// <summary>True when the gateway value is one this snapshot documents.</summary>");
        output.AppendLine("    public bool IsKnown => Known.Contains(this);");
        output.AppendLine();
        output.AppendLine($"    /// <summary>Wrap a wire value, known or not.</summary>");
        output.AppendLine("    /// <param name=\"value\">The wire value.</param>");
        output.AppendLine($"    public static {name} FromValue(string value) => new(value);");
        output.AppendLine();
        output.AppendLine("    /// <summary>The wire value.</summary>");
        output.AppendLine("    /// <param name=\"value\">The wrapper.</param>");
        output.AppendLine($"    public static implicit operator string({name} value) => value.Value ?? string.Empty;");
        output.AppendLine();
        output.AppendLine("    /// <summary>");
        output.AppendLine("    /// Wrap a wire value. Deliberately <c>explicit</c>: an implicit conversion would let");
        output.AppendLine($"    /// <c>Status = \"padi\"</c> compile as a {name} and only fail at the gateway, hours later, on");
        output.AppendLine("    /// a status that never matches. Use the constants, or <c>FromValue</c> for a value the");
        output.AppendLine("    /// gateway added after this snapshot.");
        output.AppendLine("    /// </summary>");
        output.AppendLine("    /// <param name=\"value\">The wire value.</param>");
        output.AppendLine($"    public static explicit operator {name}(string value) => new(value);");
        output.AppendLine();
        output.AppendLine("    /// <inheritdoc />");
        output.AppendLine("    public override string ToString() => Value ?? string.Empty;");
        output.AppendLine("}");
        output.AppendLine();
    }

    private static string Lower(bool value) => value ? "true" : "false";

    private static string AuthNote(string auth) => auth switch
    {
        "public" => "no credentials",
        "payment" => "payment key",
        "payout" => "payout key",
        "any" => "either key kind",
        "onboard" => "unsigned provisioning route",
        _ => auth,
    };

    private static string IdempotencyNote(Route route)
        => route.Idempotent ? ", deduplicated by Idempotency-Key" : route.Safe ? ", read-only" : string.Empty;
}
